### ISSUE TITLE
Duplicates in shortlog (mailmap needs updating)

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1010]
```
     1  Dan <ddan39ATgmail.com>
     1  Dan <ridethelightninggATgmail.com>
     1  ddan39 <ddan39ATgmail.com>
```

my email also has changed to myname at myname dot info and in git commits it has `+git` or `+github` in the address.

**Comment by ddan39** [comment]
i do not give permission for my emails to be put in any files of thise project.

the one different email was used accidentally for a single commit long ago and should never be used again, this is unnecessary. it is a private email i do not want linked to my main personal email.

thanks

**Comment by Mikaela** [comment]
> i do not give permission for my emails to be put in any files of this project.

Every time you `git commit`, your email address is stored into the git commit and is publicly available there. It's also available by adding `.patch` into end of the commit, for example with your latest commit https://github.com/ProgVal/Limnoria/commit/2fe84a3474833743ae88d19ef4899c7cac560a06.patch or latest pull request https://github.com/ProgVal/Limnoria/pull/1009.patch.

**Comment by Mikaela** [comment]
And the one commit which was from the email that you don't want visible is https://github.com/ProgVal/Limnoria/commit/54196be5093258f9b91853bb14411ec10fabe45e.patch. `git log` has flag `--author` and there is also `--grep` which make finding specific commits easy.

**Comment by nyuszika7h** [comment]
@ddan39 It's your fault for telling git to use that email address in the first place. There's nothing that can be done about that now. It already can be associated you even without adding it to the mailmap (though it could be another Dan). I'm pretty sure @ProgVal is not going to rewrite the history and force every single person who cloned and/or forked the repository to deal with the mess.

**Comment by ProgVal** [comment]
@ddan39 is not asking for removal of their email address from the history, but only for it not to be included in the mailmap.

**Comment by Mikaela** [comment]
@ProgVal how to remove the duplicates in `git shortlog -sne` without adding the address there?

> i do not give permission for my emails to be put in any files of this project.

I consider this including git log even if I am not sure how to read them without using git.

**Comment by ProgVal** [comment]
If @ddan39 wanted me to remove that address from the history, they would have asked themselves.
