### ISSUE TITLE
IRCv3?

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1015]
**For updates to this list contact @ProgVal as I am not affiliated with Limnoria and don't consider this issue as affecting me heavily, see [1](https://mikaela.info/english/2015/03/25/leaving-bots-life.html) & [2](https://mikaela.info/english/2015/05/18/life-bot-background.html).**

Should Limnoria try to follow IRCv3? It's partially supported (e.g. account-notify, whox, SASL).
- Specifications: https://github.com/ircv3/ircv3-specifications/blob/master/index#L35-103
  - Currently there seems to be just [one bot.](https://github.com/ircv3/ircv3-specifications/blob/master/index#L155)
### Base Extensions
- [x] [IRC Version 3.1: Capability Negotiation](https://github.com/ircv3/ircv3-specifications/blob/master/specification/capability-negotiation-3.1)
- [x] [IRC Version 3.1: `multi-prefix` Extension](https://github.com/ircv3/ircv3-specifications /blob/master/extensions/multi-prefix-3.1) - https://github.com/ProgVal/Limnoria/pull/1018
- [x] [IRC Version 3.1: `sasl` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/sasl-3.1)
### Optional Extensions
- [x] [IRC Version 3.1: `account-notify` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/account-notify-3.1)
- [x] [IRC Version 3.1: `away-notify` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/away-notify-3.1)
- [x] [IRC Version 3.1: `extended-join` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/extended-join-3.1)
- [x] [IRC Version 3.1: `tls` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/tls-3.1)
- Implement account-notify, extended-join and WHOX - #804
## IRCv3.2
- [x] [IRC Version 3.2: Capability Negotiation 3.2](https://github.com/ircv3/ircv3-specifications/blob/master/specification/capability-negotiation-3.2.md)
- [x] [IRC Version 3.2: Message Intents](https://github.com/ircv3/ircv3-specifications/blob/master/specification/message-intents-3.2.md)
- [x] [IRC Version 3.2: Message Tags](https://github.com/ircv3/ircv3-specifications/blob/master/specification/message-tags-3.2.md)
- [x] [IRC Version 3.2: Metadata](https://github.com/ircv3/ircv3-specifications/blob/master/specification/metadata-3.2.md)
- [x] [IRC Version 3.2: `account-tag` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/account-tag-3.2.md)
- [x] [IRC Version 3.2: `monitor` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/specification/monitor-3.2.md)
### Optional Extensions
- [x] [IRC Version 3.2: `account-tag` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/account-tag-3.2.md)
- [x] [IRC Version 3.2: `batch` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/batch-3.2.md)
- [x] [IRC Version 3.2: `cap-notify` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/cap-notify-3.2.md)
- [x] [IRC Version 3.2: `chghost` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/chghost-3.2.md)
- [ ] [IRC Version 3.2: `echo-message` Extension](http://ircv3.net/specs/extensions/echo-message-3.2.html)
- [x] [IRC Version 3.2: `invite-notify` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/invite-notify-3.2.md)
- [x] [IRC Version 3.2: `sasl` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/sasl-3.2.md)
- [x] [IRC Version 3.2: `server-time` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/server-time-3.2.md) - https://github.com/ProgVal/Limnoria/issues/1055
- [x] [IRC Version 3.2: `userhost-in-names` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/userhost-in-names-3.2.md)
## Additional Documentation
-  [x] [SASL: DH-AES mechanism](https://github.com/ircv3/ircv3-specifications/blob/master/documentation/sasl-dh-aes.md)
  - we never supported this and this shouldn't be supported.
-  [x] [SASL: DH-BLOWFISH mechanism](https://github.com/ircv3/ircv3-specifications/blob/master/documentation/sasl-dh-blowfish.md)
  - we never supported this and this shouldn't be supported.
-  [x] [Batch: `netsplit` type](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/batch/netsplit.md)

**For updates to this list contact @ProgVal as I am not affiliated with Limnoria and don't consider this issue as affecting me heavily, see [1](https://mikaela.info/english/2015/03/25/leaving-bots-life.html) & [2](https://mikaela.info/english/2015/05/18/life-bot-background.html).**

**Comment by Mikaela** [comment]
Do we support [IRC Version 3.1: `sasl` Extension](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/sasl-3.1) ? I think we do, but I am not fully sure with the issues.

**Comment by Mikaela** [comment]
Someone who knows the code better could tell which of these are already supported.

**Comment by Mikaela** [comment]
I think we might be supporting base 3.1 already with the exception of multi-prefix.

I am not fully sure on SASL being like in that standard so I am not clicking it yet until someone confirms.
https://github.com/ProgVal/Limnoria/issues/1014 seems releated.

**Comment by ProgVal** [comment]
I don't see message intents here: http://ircv3.net/irc/3.2.html
Am I missing something?

Also, account-tag is marked as being optional.

**Comment by Mikaela** [comment]
> I don't see message intents here: http://ircv3.net/irc/3.2.html

I am not sure if you have seen [this](https://mikaela.info/english/2015/03/25/leaving-bots-life.html) (maybe also [this](https://github.com/Mikaela/mikaela.github.io/issues/54)), but I haven't been doing any maintenance on this issue tracker and this issue was opened before IRCv3 got ready which means that the specifications can have changed and intents moved to [IRCv3.3](http://ircv3.net/irc/3.3.html).

> Also, account-tag is marked as being optional.

But Limnoria needs it for more reliable NickAuth which currently uses whox and account-notify. With account-tag, NickAuth would be able to identify users automatically every time they say something.

**Comment by dequis** [comment]
`self-message` should be removed from the checklist, as it's no longer an ircv3.2 capability (all clients are expected to handle that without a cap).

It was "replaced" by echo-message, which has a broader scope http://ircv3.net/specs/extensions/echo-message-3.2.html

**Comment by ProgVal** [comment]
What was `self-message`?

**Comment by dequis** [comment]
https://github.com/ircv3/ircv3-specifications/commit/1bfba47843c2526707c902034b3395af934713c8

Basically having your own hostmask in the source and someone else's nick in the target of a PRIVMSG. Usually private messages sent by another client connected to the same bouncer.

**Comment by ProgVal** [comment]
Closing as Limnoria has had full IRCv3 support for about a year now
