### ISSUE TITLE
Could NOTICEs be in loglevel INFO?

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1016]
Users use PRIVMSG to talk with the bot, but mainly services use NOTICE and some things would be easier if messages from services were visible. The bot doesn't reply to notices anyway.

Some things:
- Registration
- Managing ACL (probably should be done directly?)
- Changing password
- Managing certificates
- Managing ecdsa pubkey

**Comment by GLolol** [comment]
All incoming messages are logged to DEBUG, but not all notices are useful to be logged (e.g. ChanServ entrymsgs). The Services plugin could intercept notices from `NickServ`, though.

**Comment by Mikaela** [comment]
ENTRYMSGs might not be useful in logs, but setting flags with the bot.

**Comment by GLolol** [comment]
@ProgVal Do you think it's worth making this logging configurable (vs. always on)?

**Comment by ProgVal** [comment]
Indeed, this could be logged by Services, but only for service notices. No need to make it configurable; it would not be very verbose, and having this logging enabled by default would be helpful for new users.

**Comment by GLolol** [comment]
Ack, will work on it soon
