### ISSUE TITLE
Add option to restrict the ungrab command

### ISSUE THREAD

**Issue by wasamasa** [ProgVal/Limnoria#1025]
I've noticed that `!ungrab` can be used by anyone to remove a quotegrab.  So, if for instance Alice wrote "Don't grab this" and Bob did `!grab Alice`, Eve could do `!ungrab` although Eve is neither someone with elevated capabilities nor the grabbed nor the grabbee.

Therefore I propose an option for the `quotegrab` plugin that once enabled makes a check for the identity of Eve mandatory.  If this check fails the criteria outlined above, an appropriate error message should be displayed.  How does this proposal sound?

**Comment by Mikaela** [comment]
This might not be what you are looking for, but you can prevent those commands from being used by

* `defaultcapability add -quotegrabs.grab`
* `defaultcapability add -quotegrabs.ungrab`

and manually allow some people to do that with

* `admin capability add username quotegrabs.grab` etc.

**Comment by wasamasa** [comment]
I've looked a bit closer at the sources and found out that the bot only stores nicknames of all persons involved and a hostmask. Therefore, checking whether the ungrabber is authenticated with the bot will not work out.

What could work out would be checking for nickname matches and if there is such a match, check whether the person involved is identified with nickserv. A possible approach for the latter is demonstrated with the NickAuth plugin which apparently does a whois and checks whether the nick name is reported as logged in by the 330 handler.
