### ISSUE TITLE
A quick way to ungrab the last quoted quote

### ISSUE THREAD

**Issue by grawity** [ProgVal/Limnoria#1027]
Currently, whenever someone gets a particularly bad quote from `quotegrabs random`, they cannot remove it directly; one has to dig through many pages of `quotegrabs list/search <nick>` to find the quote ID, and only then give it to `ungrab`.

But, for example, in #xkcd, one can ask Bucket "what was that?" for information about the last quote/factoid that was most recently said to the channel, or "forget that" to delete the quote/factoid entirely.

It would be useful to have the same for QuoteGrabs &ndash; either a way to remove the last quote...

    (user) !rq
    (bot) <fred> dicks
    (user) !ungrab last
    (bot) Quote #12345 "<fred>..." removed.

...or, alternatively, to always see quote IDs in `quotegrabs random`:

    (user) !rq
    (bot) #12345: <fred> dicks
    (user) !ungrab 12345
    (bot) Quote #12345 removed.

**Comment by ProgVal** [comment]
Why did you close it?
