### ISSUE TITLE
Verify server SSL certificates

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1031]
As most of networks have invalid certificates, there should also be option for setting which certificate (SHA256) fingerprints to trust which probably should allow multiple.

Many people might also want to have option to not care about invalid certificates, but I don't think one should be included.

**Comment by GLolol** [comment]
Honestly, I feel like this is going to cause the same issue I had with ZNC... 80% of my networks not being able to connect and me having to add the certificates for all of them manually :/

**Comment by Mikaela** [comment]
**TL;DR: if you don't verify SSL certificates, don't use SSL!** https://mikaela.info/english/2015/02/24/znc160-ssl.html

**Comment by GLolol** [comment]
Yeah, yeah, been there read that. But I'd rather have at least some encryption than having everything exposed in plain text. Maybe people would be more inclined to issue valid certs if they weren't so **expensive and frustrating to set up**.

... But that's a rant for another day :)

**Comment by Mikaela** [comment]
* [DANE](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities) is getting attention.
    * https://github.com/weechat/weechat/pull/121
    * https://github.com/znc/znc/issues/784
* I have seen recommendations of [StartSSL](http://www.startssl.com/).
* [Let's Encrypt](https://letsencrypt.org/) might also change the situation.

**Comment by ProgVal** [comment]
Note: implementing this using `ssl.SSLContext` would break compatibility with Python < 2.7.9

**Comment by MrBenC** [comment]
Would using PyOpenSSL be an option?  This would have unfortunate side-effects such as refactoring as well as an additional dependency users would have to install.

I came across this: http://blog.san-ss.com.ar/2012/05/validating-ssl-certificate-in-python.html

Ben

**Comment by ProgVal** [comment]
One could write two different codes, one for Python's `ssl` module and one for PyOpenSSL

**Comment by ProgVal** [comment]
Actually, I'm too lazy to write and extensively test alternative code only to support old Python version. If someone comes up with PyOpenSSL code *and* tests for it, I'll accept it, but I won't do it myself.
So, for now, Limnoria will only use the core `ssl` module.
