### ISSUE TITLE
Limnoria requires networks.network.sasl.username to be set for SASL EXTERNAL

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1052]
SASL EXTERNAL doesn't use that, so something is wrong with Limnoria. It should be automatically attempted when certfp is configured without caring about other SASL settings.

**Comment by ProgVal** [comment]
What if one wants to use CertFP without SASL?

**Comment by Mikaela** [comment]
And why would someone want to do that? If the network doesn't support SASL *, it's not even attempted.

**Comment by ProgVal** [comment]
good point

**Comment by ProgVal** [comment]
I think this is fixed now.
