### ISSUE TITLE
Support cap server-time & self-message

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1055]
- https://github.com/ircv3/ircv3-specifications/blob/master/extensions/server-time-3.2.md
- https://github.com/ircv3/ircv3-specifications/blob/master/extensions/self-message-3.2.md

This could be helpful with servers that support server-time (for example Mammon (experimental)) and ZNC. The capability is called as `server-time`, but provider specific capability is e.g. `znc.in/server-time-iso`.

**Comment by Mikaela** [comment]
https://github.com/ircv3/ircv3-specifications/blob/master/specification/capability-negotiation-3.1#L162

but we should already support this.

**Comment by GLolol** [comment]
What would be the benefits of supporting this?

**Comment by ProgVal** [comment]
+1 @GLolol 

And that would make timestamps inconsistent (in ChannelLogger, for instance) if the server and the system running the bot are not synchronized.

**Comment by Mikaela** [comment]
With ZNC the first benefit is not having bufer playback messing it.

Elsewhere it would make the bot use the time from server so all parties see the same time. ChannelLoger wouldn't get inconsistent as the bot listens to time which server gives. The bot can use it's own timezone.

**Comment by ProgVal** [comment]
On 20/02/2015 19:15, Mikaela Suomalainen wrote:
> Elsewhere it would make the bot use the time from server so all parties see the same time. ChannelLoger wouldn't get inconsistent as the bot listens to time which server gives. The bot can use it's own timezone.

Not for logging its own messages…

**Comment by Mikaela** [comment]
I believe that it's supposed to be logging using the server time for messages that come from the server meaning ChannelLogger.

**Comment by ProgVal** [comment]
So it will use server time for incoming messages and its own time for outgoing messages.

**Comment by Mikaela** [comment]
I think there should also be support for self-message and using the server time for also it's own messages.

* https://github.com/ircv3/ircv3-specifications/blob/master/extensions/self-message-3.2.md

**Comment by ProgVal** [comment]
That would make message handling unnecessarily complicated

**Comment by GLolol** [comment]
Why would you need a bot behind ZNC just for logging? Just turn off playback and log at the bouncer side.

**Comment by DarthGandalf** [comment]
> The capability is called as `server-time`, but provider specific capability is e.g. `znc.in/server-time-iso`.

This is not exactly right. It's in `znc.in` namespace to protect from any possible changes in the 3.2 spec, which is still not finalized. We already had to change wire format, hence the `-iso` part.
When IRCv3.2 is out, we'll just rename our implementation to `server-time`. (perhaps for some time it'll be available under both names for compatibility with clients which already request `znc.in/server-time-iso`)

**Comment by Mikaela** [comment]
> Why would you need a bot behind ZNC just for logging? Just turn off playback and log at the bouncer side.

I don't think I have talked about logging other than the ChannelLogger which seems to worry @ProgVal . There are also networks that support server-time, currently just `irc.dereferenced.org` port 6667 (no SSL yet), but when IRCv3.2 is released or sooner, other IRCds might implement it too (Charybdis?).

**Comment by ProgVal** [comment]
Closing, as `server-time` and `echo-message` having been supported for a couple of years
