### ISSUE TITLE
supybot-test dumps temporary folders into the working directory

### ISSUE THREAD

**Issue by NP-Hardass** [progval/Limnoria#1061]
The current behavior when running supybot-test is to create several folders and files in the current working directory.  This has several side effects.  supybot-test cannot be run while the user doesn't have write permissions to cwd, supybot cannot be run more than once from within plugins-dir because it attempts to interpret its own leftover test directories as plugins, and supybot-test has the potential to clobber other files/folders when running in a directory in which the folders that it uses already exist. 
The temporary files/folders created by the supybot-test are left behind.  If there is a legitimate use for them, then they should be removed in all instances except where a flag is raised (so that normal users aren't burdened with extra files/folders) 

``` pseudocode
if user can write to /tmp
  TESTDIR=`mktemp -d`
else
  mkdir -p ~/.tmp
  TESTDIR=`mktemp -d -p  ~/.tmp`
create temp folders/files in TESTDIR
run test suite
if keep testdir flag
  rm -rf TESTDIR
```

**Comment by Mikaela** [comment]
Concerns:
* Cross-platform support
    * Windows
* being Python

**Comment by NP-Hardass** [comment]
Sure...
I gave an example of good behavior, not a final implementation...

**Comment by ProgVal** [comment]
https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory

**Comment by jamessan** [comment]
The main reason the files aren't deleted is so that there's information to inspect when there are test failures.  Granted, the default behavior could be to remove the files if everything passes.
