### ISSUE TITLE
Channel: if the channel is in autojoin and bot is not there, make part command remove it from autojoin

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1068]
This is very annoying when the bot is banned or similar (channel forward?) and ZNC behaves like this with `/part` on banned channel.

**Comment by GLolol** [comment]
The `part` command [already does this](https://github.com/ProgVal/Limnoria/blob/testing/plugins/Channel/plugin.py#L979-L983).

ZNC is a special case because you have to explicitly call `/part` again after you're banned. I don't like this behaviour either, but it's not the bot's fault.

**Comment by Mikaela** [comment]
@GLolol the part command doesn't do this or it's broken.

**Comment by jamessan** [comment]
The part command does do this.  See [this code](https://github.com/ProgVal/Limnoria/blob/7757f3a1b4943077f6a871e3f4d3e1fff04a6086/plugins/Channel/plugin.py#L981).

**Comment by GLolol** [comment]
@Mikaela This might be a ZNC specific issue then, as other clients will see the same thing.

**Comment by Mikaela** [comment]
I am not sure what you are talking about and I wish to not be contacted about anything Supybot related as people wished for me to leave as I am autistic and trans. For more information, [please see my blog.](https://mikaela.info/english/2015/03/25/leaving-bots-life.html)

I am also closing this issue now and unsubscribing (again).
