### ISSUE TITLE
Add support for Q/Quakenet

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1077]
Documentation: https://www.quakenet.org/development/challengeauth

Personally I believe this shouldn't be done and Quakenet should do like other networks and implement IRCv3.1 SASL which is already supported:
* https://github.com/ircv3/ircv3-specifications/blob/master/extensions/sasl-3.1

It also wouldn't hurt if Limnoria implemented IRCv3.2 SASL which features SASL REAUTH:
* https://github.com/ircv3/ircv3-specifications/blob/master/extensions/sasl-3.2.md

**Comment by Mikaela** [comment]
Quakenet has been requested to take care of this issue.

* https://twitter.com/Inaneierase/status/577176494763552768
* https://twitter.com/Inaneierase/status/577176770182541312

I am hoping they understand to start supporting SASL and preferably SSL.

Elsewhere there were pointed some issues about Quakenet including:
* Max password length being 8 characters
* The challengeauth using MD5 which is deprecated and so is it's follower SHA1.
* They don't support TLS claiming it to be pointless.

**Comment by GLolol** [comment]
https://github.com/GLolol/Supybot-Quakenet... I don't like their auth system either, but that's not up to me :)

**Comment by Mikaela** [comment]
That should probably ship with Limnoria, but it would be stupid as it's only for single dying network.

**Comment by GLolol** [comment]
They're not a dying network, **and your complaining does not help**.
