### ISSUE TITLE
Network whois has issues with color codes in real names.

### ISSUE THREAD

**Issue by SoniEx2** [ProgVal/Limnoria#1083]
Should reset color after name.

**Comment by GLolol** [comment]
Color codes don't belong in nicks. That violates basic IRC protocol rules...

**Comment by SoniEx2** [comment]
Real names, not nicks. You can put anything in real names.

**Comment by GLolol** [comment]
This should be fixed in testing, which merged in @jamessan's commit above.

**Comment by GLolol** [comment]
Fixed according to the above commit.
