### ISSUE TITLE
"Error: You need the python-twitter library." even with package(s) installed

### ISSUE THREAD

**Issue by Agent-Isai** [ProgVal/Limnoria#1084]
For some reason, when I load twitter it says "[00:00] (@Bot) Error: You need the python-twitter library.", I already installed python-oauth2 and python-twitter via pip (I installed it with the --user option). Any idea why?

**Comment by ProgVal** [comment]
(I don't think this issue is related to Limnoria)

did you restart the bot after installing python-twitter?

**Comment by Agent-Isai** [comment]
I did
