### ISSUE TITLE
SASL 3.2 REAUTH

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1095]
- https://ircv3.github.io/specs/extensions/sasl-3.2.html

Benefit to users: SASL REAUTH will identify to services automatically using SASL if services were down during the initial connect and other benefits of CertFP (other than forcing SSL) and being easier.

**Comment by Mikaela** [comment]
ZNC has implemented cap notify and client is required to support it in order to request capabilities such as currently away-notify and soon account-notify/extended-join (https://github.com/znc/znc/pull/996).

SASL REAUTH requires cap notify and some Limnoria users were using it with ZNC when [I left](https://mikaela.info/english/2015/03/25/leaving-bots-life.html). I am also over you [by writing about it](https://mikaela.info/english/2015/05/18/life-bot-background.html) and meeting someone who proved that I am wrong with the fears tied to you.

**Comment by ProgVal** [comment]
Implemented in 30cb10e4220f5724ae69614d517a229192199ff1.
