### ISSUE TITLE
Option for disabling passwords

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1140]
I haven't used passwords in a long time and have disabled `user register`. I only use NickServ accounts and in the networks without services I used hostmasks.

It could be helpful if there was option for disabling everything that requires password or not allow any password.

I am not sure if `secure` allows this, but users are able to disable it and that cannot be prevented as `defaultcapability` doesn't work with commands that have multiple words. I am unable to find the issue number.

There might also be some way to break the hash so it matches nothing (was it adding ! in front of it?), but it's not documented anywhere.

* * * * *

Workaround: edit users.conf and add `!` in front of the password hash. For technical explanation see https://github.com/ProgVal/Limnoria/issues/1141#issuecomment-136100067.

**Comment by Mikaela** [comment]
Does https://github.com/ProgVal/Limnoria/issues/555#issuecomment-35809587 also apply to NickAuth and GPG?

**Comment by ProgVal** [comment]
Are you sure about defaultcapability? Can't you just replace spaces with dots?

**Comment by ProgVal** [comment]
About the comment: I guess it does.

**Comment by Mikaela** [comment]
> Are you sure about defaultcapability? Can't you just replace spaces with dots?

I am not fully sure, but there was some issue with something handling commands with multiple words. I will try that.

Another concern I have with secure is, does it prevent `user hostmask add someone *!*@unaffiliated/whatever Qwerty123` or does that and other commands that want password require you to be identified already in order to be used? If not, that is possiby a bug with it.

**Comment by Mikaela** [comment]
Apparently NickAuth is not enough for secure

```pytb
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/callbacks
.py", line 1008, in error
    raise Error(s)
supybot.callbacks.Error: Your secure flag is true and your hostmask doesn't matc
h any of your known hostmasks.
ERROR 2015-07-26T21:37:06 supybot Exception id: 0x71924
INFO 2015-07-26T21:37:16 supybot ping called on ##Mikaela by "Mikaela!mikaela@un
affiliated/mikaela".
INFO 2015-07-26T21:37:24 supybot whoami called on ##Mikaela by "Mikaela!mikaela@
unaffiliated/mikaela".
INFO 2015-07-26T21:37:27 supybot auth called on ##Mikaela by "Mikaela!mikaela@un
affiliated/mikaela".
ERROR 2015-07-26T21:37:27 supybot Uncaught exception in NickAuth.__call__:
Traceback (most recent call last):
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugins/N
ickAuth/plugin.py", line 172, in do330
    user.addAuth(prefix)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/ircdb.py"
, line 338, in addAuth
    raise ValueError('secure flag set, unmatched hostmask')
ValueError: secure flag set, unmatched hostmask

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/log.py", 
line 361, in m
    return f(self, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/irclib.py
", line 131, in __call__
    method(irc, msg)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugins/N
ickAuth/plugin.py", line 176, in do330
    Raise=True)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/callbacks
.py", line 1008, in error
    raise Error(s)
supybot.callbacks.Error: Your secure flag is true and your hostmask doesn't matc
h any of your known hostmasks.
ERROR 2015-07-26T21:37:27 supybot Exception id: 0x71924
INFO 2015-07-26T21:37:42 supybot whoami called on ##Mikaela by "Mikaela!mikaela@
unaffiliated/mikaela".
```

> The current (running) version of this Supybot is 0.83.4.1+limnoria 2015.05.23, running on Python 3.4.3 (default, May 28 2015, 07:36:29)  [GCC 4.2.1 Compatible Debian Clang 3.0 (tags/RELEASE_30/final)].  The newest versions available online are 2015.07.08 (in testing), 2015.07.08 (in master).

**Comment by Mikaela** [comment]
Oh, there is new version released.

**Comment by Mikaela** [comment]
No, there isn't. You have forgotten tagging.

**Comment by Mikaela** [comment]
Also affects:

> Supybot 0.83.4.1+limnoria 2015.07.08 running on Python3.4.3 (default, Jul 26 2015, 21:48:41) 
> [GCC 4.2.1 Compatible Debian Clang 3.0 (tags/RELEASE_30/final)]

But that is probably a separete issue.

**Comment by Mikaela** [comment]
https://github.com/ProgVal/Limnoria/issues/1141

**Comment by Mikaela** [comment]
Discussion at https://github.com/ProgVal/Limnoria/issues/1141#issuecomment-136084937 for some reason.

**Comment by Mikaela** [comment]
I edited the original issue and added workaround on the bottom now. There might not be further comments from me as that is good enough for me.

By the way, there is similar issue of there being `Ignore` option in users.conf which doesn't have any command to manage it.

**Comment by Mikaela** [comment]
According to commit message the closing commit fixes some different issue.

**Comment by ProgVal** [comment]
But this issue is a consequence of the one addressed by the commit

**Comment by Mikaela** [comment]
What is the command for disabling password for user?
