### ISSUE TITLE
Secure doesn't consider NickAuth as secure

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1141]
```pytb
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/callbacks
.py", line 1008, in error
    raise Error(s)
supybot.callbacks.Error: Your secure flag is true and your hostmask doesn't matc
h any of your known hostmasks.
ERROR 2015-07-26T21:37:06 supybot Exception id: 0x71924
INFO 2015-07-26T21:37:16 supybot ping called on ##Mikaela by "Mikaela!mikaela@un
affiliated/mikaela".
INFO 2015-07-26T21:37:24 supybot whoami called on ##Mikaela by "Mikaela!mikaela@
unaffiliated/mikaela".
INFO 2015-07-26T21:37:27 supybot auth called on ##Mikaela by "Mikaela!mikaela@un
affiliated/mikaela".
ERROR 2015-07-26T21:37:27 supybot Uncaught exception in NickAuth.__call__:
Traceback (most recent call last):
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugins/N
ickAuth/plugin.py", line 172, in do330
    user.addAuth(prefix)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/ircdb.py"
, line 338, in addAuth
    raise ValueError('secure flag set, unmatched hostmask')
ValueError: secure flag set, unmatched hostmask

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/log.py", 
line 361, in m
    return f(self, *args, **kwargs)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/irclib.py
", line 131, in __call__
    method(irc, msg)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/plugins/N
ickAuth/plugin.py", line 176, in do330
    Raise=True)
  File "/home/users/mikaela/.local/lib/python3.4/site-packages/supybot/callbacks
.py", line 1008, in error
    raise Error(s)
supybot.callbacks.Error: Your secure flag is true and your hostmask doesn't matc
h any of your known hostmasks.
ERROR 2015-07-26T21:37:27 supybot Exception id: 0x71924
INFO 2015-07-26T21:37:42 supybot whoami called on ##Mikaela by "Mikaela!mikaela@
unaffiliated/mikaela".
```

Personally I believe NickAuth is more secure than hostmask and secure should allow `nickauth auth` and the automatic identification as hostmask.

> Supybot 0.83.4.1+limnoria 2015.07.08 running on Python3.4.3 (default, Jul 26 2015, 21:48:41)
> [GCC 4.2.1 Compatible Debian Clang 3.0 (tags/RELEASE_30/final)]

Moved from https://github.com/ProgVal/Limnoria/issues/1140#issuecomment-125026052

**Comment by ProgVal** [comment]
Actually, NickAuth shouldn't authenticate users if their hostmask doesn't match and their secure flag is on.
NickAuth enforces this behavior with 330 (WHOIS replies sent because of @auth).
But not with JOIN or 354 (ie. WHOX), and that's the actual bug.

I think the best thing to do is to fix the latter behavior. Do you agree?

About your statement “NickAuth is more secure than hostmask”: in theory, it is true. However, whatever the authentication method, Limnoria ends up using temporary hostmasks, even with NickAuth. That's why the “secure” flag only considers hostmask authentication secure.

**Comment by Mikaela** [comment]
How do I disable using passwords for users? I thought `secure` was the way.

I believe that secure in the way how you treat it currently is stuck in the past.

1. If hostmask matches, user is automatically identified, no further proof of identification isn't required.
2. Assuming the user is on modern network, there is NickServ and they most likely have a vhost which is activated on login which makes it as secure as nickauth.
3. What if there is IRCd side cloaking module enabled? Part of the cloak is always random so hostmask isn't very useful identification method. With full cloaking hostmask identification becomes even more difficult.

**Comment by Mikaela** [comment]
> How do I disable using passwords for users? 

Now I tried another way, the `passwd -l` way. I prepended `!` to all passwords and after `config reload` the bot doesn't lose users.

I wasn't able to login as random user with wrong password, but is the password really unusable or did I only change the password?

* * * * *

Quoting the fine manual for passwd:

```man
       -l, --lock
           Lock the password of the named account. This option disables a
           password by changing it to a value which matches no possible
           encrypted value (it adds a '!' at the beginning of the password).

           Note that this does not disable the account. The user may still be
           able to login using another authentication token (e.g. an SSH key).
           To disable the account, administrators should use usermod
           --expiredate 1 (this set the account's expire date to Jan 2, 1970).

           Users with a locked password are not allowed to change their
           password.
```

**Comment by ProgVal** [comment]
On 30/08/2015 06:52, Mikaela Suomalainen wrote:
> I believe that secure in the way how you treat it currently is stuck in the past.

Why?

> 3. What if there is IRCd side cloaking module enabled? Part of the cloak is always random so hostmask isn't very useful identification method. With full cloaking hostmask identification becomes even more difficult.

Cloaks are hashs of real hostmasks, not random strings, right?

**Comment by Mikaela** [comment]
> Cloaks are hashs of real hostmasks, not random strings, right?

For some reason at least Charybdis cloaking changes ordering of letters on PirateIRC from what I understood and observed.

**Comment by ProgVal** [comment]
Looks like a bug / bad feature on their side

**Comment by Mikaela** [comment]
I can be wrong.

Did you see https://github.com/ProgVal/Limnoria/issues/1141#issuecomment-136085368?

**Comment by ProgVal** [comment]
> I wasn't able to login as random user with wrong password, but is the password really unusable or did I only change the password?

Passwords are stored as SHA (1 or 2, I dont remember) hashs. As hashs don't contain `!` characters, no password can have a hash equal to the one you set. So there is no password at all.
Actually, even if you replaced a letter by another one, finding a password with the new hash would be equivalent to breaking the hash algorithm.

**Comment by Mikaela** [comment]
So now users cannot login with it or change passwords or anything that requires password? #1140 can probably be closed them..

**Comment by Mikaela** [comment]
Wrong button, I am not sure what you were going to do with this issue, my main one was #1440.

**Comment by ProgVal** [comment]
> So now users cannot login with it or change passwords or anything that requires password?

Indeed. But having an option to do that without editing files would be nice

**Comment by ProgVal** [comment]
Can I close this issue?

**Comment by Mikaela** [comment]
Probably as we seem to disagree on the point of secure and it doesn't even do what I want it to do.
