### ISSUE TITLE
Allow customizing the "whoami" unidentified message

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1142]
Like `help` can be customized.

> I don't recognize you. You can message me either of these two commands: "user identify <username> <password>" to log in or "user register <username> <password>" to register.

I personally don't give users passwords (`supybot-adduser -u someone -p $(pwgen -s 50) -c \#channel,op`) and just identify them with hostmask or NickServ account and also have disabled registration, so these instructions don't apply to my instance.

I would like to change it to e.g. "You aren't identified. If you think you should be, use the 'auth' command. If you aren't registered and fill the criteria of https://mikaela.info/bot#users, ask Mikaela."

**Comment by GLolol** [comment]
Fixed by https://github.com/ProgVal/Limnoria/commit/b46ea6f6bced7e10298a6a24506db6e1baceb279 as part of #1273
