### ISSUE TITLE
Network password fails

### ISSUE THREAD

**Issue by Agent-Isai** [ProgVal/Limnoria#1149]
For some reason, when I connect to a BNC (that requires password). It does nothing:

Isai@irc:~/Bot$ supybot Bot.conf                                INFO 2015-08-09T11:01:00 Creating new Irc for freenode.
INFO 2015-08-09T11:01:00 freenode: Queuing PASS command, not logging the password.
INFO 2015-08-09T11:01:01 Connecting to localhost:2222.
INFO 2015-08-09T11:01:01 Loading plugins (connecting to freenode).
INFO 2015-08-09T11:01:01 Starting HTTP server: server at :: 8080
WARNING 2015-08-09T11:01:01 Failed to load RSS: import error (No module named 'feedparser').
INFO 2015-08-09T11:01:01 freenode: Server acknowledged capabilities: multi-prefix
ERROR 2015-08-09T11:01:01 Unhandled error message from server: IrcMsg(prefix="irc.znc.in", command="410", args=('Bot', 'END :Invalid CAP subcommand'))

Then it states the connection got closed because it supplied no password. On a different machine (with an older version of Limnoria), network password works perfectly. Is this an error by my machine (I've reinstalled many times and this continues to happen) or is it an error affecting all of Limnoria?

**Comment by ProgVal** [comment]
I have a similar issue for awhile, but I am unable to understand how to solve it or where it comes from.

Is there any difference between your two machines? Limnoria version, servers you connect to, …

**Comment by Agent-Isai** [comment]
Only the versions, one is running a version from December 24, 2014 while a different one is running the newest version. I don't think the OS should matter as one machine runs Debian 7 and the other one runs Debian 8.

**Comment by GLolol** [comment]
Are the bots using Python 2 or 3?

**Comment by Agent-Isai** [comment]
Both are using Python 3, I tried using the Bot in Python 2 but I get the same result

**Comment by Agent-Isai** [comment]
Is there a way to make the Bot execute a command on connect? If so, I could make my bot execute /quote PASS <username/<network>:<password>.

**Comment by Mikaela** [comment]
Yes, if you want the command to be same on all networks. https://github.com/ProgVal/Supybot-plugins/tree/master/Trigger

**Comment by ProgVal** [comment]
This is a bug in ZNC, which has been fixed: https://github.com/znc/znc/pull/1013
