### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by Connor1301** [ProgVal/Limnoria#1202]
On windows 10 after setting up config file when you go to run it " File "C:\filelocation", line 18
supybot.nick: supybotnickname
                    ^(pointing at ':' )
SyntaxError: invalid syntax"

**Comment by GLolol** [comment]
Can you attach a more complete version of your config?

**Comment by ProgVal** [comment]
It looks like you are trying to run the config file with Python.
You are supposed to run Limnoria with Python, and Limnoria reads the config file:

```
python C:\Python34\Scripts\supybot yourbotnick.conf
```

http://doc.supybot.aperio.fr/en/latest/use/install.html#install-supybot

**Comment by ProgVal** [comment]
Can I close the issue?
