### ISSUE TITLE
Should each IRC network object have its own, distinct irc.state.history?

### ISSUE THREAD

**Issue by GLolol** [ProgVal/Limnoria#1211]
I noticed that the `irc.state.history` attribute stores the command history of _all_ networks, instead of just the ones associated with that network. Since other `irc.state` variables (IRCd name, available modes, etc.) are all specific to each connection, it would make sense if `irc.state.history` was also connection-specific. Is this an oversight or simply a design decision I wasn't aware of?

The rationale for this is a sed-style replacer bot that runs on multiple networks, but in two different channels with the same name (e.g. `#chat`). The bot starts to confuse messages from the two channels, since messages from both are added to the same `irc.state.history`.

**Comment by ProgVal** [comment]
Is there no way to know where a message in `irc.state.history` is from?

**Comment by GLolol** [comment]
`irc.state.history` just stores a list of `IrcMsg` objects.

```
16:45 <~GLolol> `eval dir(msg)
16:45 <@Lily> ​['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__req__', '__rne__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '_hash', '_len', '_repr', '_str', 'args', 'command', (1 more message)
16:45 <~GLolol> `more
16:45 <@Lily> ​'host', 'nick', 'prefix', 'reply_env', 'server_tags', 'tag', 'tagged', 'tags', 'time', 'user']
```

I don't see anything showing the network here. Adding that to `IrcMsg` would be the easy solution, I assume.

**Comment by GLolol** [comment]
Okay, apparently this is *easy* to fix. How would I go about adding this?

**Comment by ProgVal** [comment]
Actually, now I think about it, you can already do that by looking at `msg.args`

**Comment by GLolol** [comment]
`msg.args[0]` for PRIVMSGs is the channel, right? It doesn't tell me what network it is.

```
16:01 <~GL> `eval "msg.args[0]"
16:01 <@Lily> ​'#test'
16:02 <~GL> `eval "irc.state.history[-1].args[0]"
16:02 <@Lily> ​'#test'
```

**Comment by ProgVal** [comment]
oh, indeed, sorry.

I think the best solution would be to make `irc.state.history` only contain messages for one network. It would be more consistant with other attributes of `IrcState`, which are network-specific; and I don't feel like adding an extra field to `IrcMsg` (which already has a lot of them).

**Comment by GLolol** [comment]
A closer look at the source tells me that `msg.tagged('receivedBy')` stores the `Irc` object where the message was received. So there's a workaround, but I still think the current `irc.state.history` isn't the most intuitive.
