### ISSUE TITLE
RSS plugin does not use the (HTTP) proxy configuration option

### ISSUE THREAD

**Issue by JunaidLoonat** [ProgVal/Limnoria#1234]
The `proxy` configuration option has the description of "Determines what proxy all HTTP requests should go through".

However, even if correctly configured, the [RSS plugin](https://github.com/ProgVal/Limnoria/tree/master/plugins/RSS) does not make use of any the HTTP proxy as one would expect. Instead, direct connections are made to retrieve the feeds for parsing.

**Comment by ProgVal** [comment]
Could you test if that patch works?

```diff
diff --git a/plugins/RSS/plugin.py b/plugins/RSS/plugin.py
index f1a7bbc..1820e0c 100644
--- a/plugins/RSS/plugin.py
+++ b/plugins/RSS/plugin.py
@@ -52,6 +52,11 @@ import supybot.callbacks as callbacks
 from supybot.i18n import PluginInternationalization, internationalizeDocstring
 _ = PluginInternationalization('RSS')
 
+if minisix.PY2:
+    from urllib2 import ProxyHandler
+else:
+    from urllib.request import ProxyHandler
+
 def get_feedName(irc, msg, args, state):
     if ircutils.isChannel(args[0]):
         state.errorInvalid('feed name', args[0], 'must not be channel names.')
@@ -289,9 +294,13 @@ class RSS(callbacks.Plugin):
     # Feed fetching
 
     def update_feed(self, feed):
+        handlers = []
+        if utils.web.proxy():
+            handlers.append(ProxyHandler(
+                {'http': utils.force(utils.web.proxy())}))
         with feed.lock:
             d = feedparser.parse(feed.url, etag=feed.etag,
-                    modified=feed.modified)
+                    modified=feed.modified, handlers=handlers)
             if 'status' not in d or d.status != 304: # Not modified
                 if 'etag' in d:
                     feed.etag = d.etag
```

**Comment by JunaidLoonat** [comment]
Thanks, the patch worked for Python 2(.7.6) but not for Python 3(.4.3)
I'll take a stab at (re-)wiring the RSS plugin back to util-web so there's no proxy configuring occurring within a plugin.

In addition, I'll try to push through other internal changes specifically with regards to HTTPS proxy usage and util-web improvements.

**Comment by ProgVal** [comment]
On 25/04/2016 07:53, Junaid Loonat wrote:
> Thanks, the patch worked for Python 2(.7.6) but not for Python 3(.4.3)

Does it error, or just ignores the proxy setting?

> I'll take a stab at (re-)wiring the RSS plugin back to util-web so there's no proxy configuring occurring within a plugin.

That would be nice

> In addition, I'll try to push through other internal changes specifically with regards to HTTPS proxy usage and util-web improvements.

Not sure what you want to do, but feel free to send pull requests

**Comment by JunaidLoonat** [comment]
Separate 'http' and 'https' items are required to configure proxy usage for both schemes.
e.g. {'http': ..., 'https': ...}

I've submitted a pull request, #1235, to add HTTPS proxy use to the internal util-web component.

Strangely enough, after some environment fiddling and rebuilding, I don't experience anymore issues with your patch under Python 3. I guess my Python gremlins have gone back to sleep for now.
