### ISSUE TITLE
Web: allow hiding the (at example.com) in titlesnarfer or replacing it with not link

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1236]
* `<Euforia> The current (running) version of this Supybot is 2016.03.21, running on Python 3.5.1 (default, Jan  6 2016, 10:18:06)  [GCC 4.7.2].  The newest versions available online are 2016.03.21 (in master), 2016.04.24 (in testing).`

When someone links to some page, titlesnarfer fetches the title and says at example.org which makes some clients (or Telegram) fetch the title and picture for that domain. As it was already linked before Limnoria, there is spam due to it.

What I propose would be just not showing it or saying `(at mikaela dot info)` instead of saying the actual domain or preferably option allowing to choose either the current behaviour or either of these. I prefer replacing . with "dot".

**Comment by GLolol** [comment]
I feel like it's a misdesign in the client to not allow hiding link previews. But turning off the (at x.yz) part entirely would be a welcome change IMO

**Comment by Mikaela** [comment]
> I feel like it's a misdesign in the client to not allow hiding link previews. 

Screenshot probably explains the problem.

![Telegram](https://teleuforia.mikaela.info/vKZ1Z6oW/file_208.jpg)

I haven't seen Telegram option to turn off the link previews, but they are helpful in all cases except if there is bot like Limnoria doing titlefetching and linking to the domain.

I also imagine that IRC clients having the same behaviour would turn it off/on globally which would also be harmful as not every channel has a titlefetcher.

**Comment by Mikaela** [comment]
Accidentally gotten even more clear screenshot of the problem.

![screenshot](https://teleuforia.mikaela.info/QbTWE10O/file_210.jpg)

**Comment by GLolol** [comment]
I understand the issue, but I still think it's a misdesign in Telegram's part.

**Comment by ProgVal** [comment]
Skype Web and Skype for Android have the same “feature”.

**Comment by Mikaela** [comment]
The TeleIRC issue is tracked at https://github.com/FruitieX/teleirc/issues/140 .
