### ISSUE TITLE
[Testing Branch] Google: Any 'google' call returns "No results found." for any search query.

### ISSUE THREAD

**Issue by teward** [ProgVal/Limnoria#1237]
Tested today, in #limnoria-bots on IRC, the "Testing" branch shows no output for any Google queries.  This test was done including the recent commits to use web scraping instead of the AJAX API which was discontinued.

Debug level logging here from the bot during the calls to the Google plugin, in case it helps:

```
INFO 2016-05-04T16:13:24 google called on #limnoria-bots by "teward!teward@ubuntu/member/teward".
DEBUG 2016-05-04T16:13:24 args before <getopts for {'filter': '', 'language': 'something'}>: ['Test']
DEBUG 2016-05-04T16:13:24 args after <getopts for {'filter': '', 'language': 'something'}>: ['Test']
DEBUG 2016-05-04T16:13:24 args before <context for text>: ['Test']
DEBUG 2016-05-04T16:13:24 args after <context for text>: []
DEBUG 2016-05-04T16:13:24 State before call: State(args=[[], 'Test'], kwargs={}, channel=None)
DEBUG 2016-05-04T16:13:25 Outgoing message (freenode): PRIVMSG #limnoria-bots :teward: No matches found.

DEBUG 2016-05-04T16:14:13 Incoming message (freenode): :teward!teward@ubuntu/member/teward PRIVMSG #limnoria-bots :ArcTest: google Test --language en --filter off
DEBUG 2016-05-04T16:14:13 findCallbacksForArgs: [(<Google Google <Google.plugin.Google object at 0x7f6abd55e590>>, ['google'])]
DEBUG 2016-05-04T16:14:13 Spawning thread Thread #4 (for Google.['google']) (args: (['google'], <supybot.callbacks.NestedCommandsIrcProxy object at 0x7f6ab7fa5910>, IrcMsg(prefix="teward!teward@ubuntu/member/teward", command="PRIVMSG", args=('#limnoria-bots', 'ArcTest: google Test --language en --filter off')), ['Test', '--language', 'en', '--filter', 'off']))
DEBUG 2016-05-04T16:14:13 Spawning thread "Thread #4 (for Google.['google'])".
INFO 2016-05-04T16:14:13 google called on #limnoria-bots by "teward!teward@ubuntu/member/teward".
DEBUG 2016-05-04T16:14:14 args before <getopts for {'filter': '', 'language': 'something'}>: ['Test', '--language', 'en', '--filter', 'off']
DEBUG 2016-05-04T16:14:14 args after <getopts for {'filter': '', 'language': 'something'}>: ['Test', '--language', 'en', '--filter', 'off']
DEBUG 2016-05-04T16:14:14 args before <context for text>: ['Test', '--language', 'en', '--filter', 'off']
DEBUG 2016-05-04T16:14:14 args after <context for text>: []
DEBUG 2016-05-04T16:14:14 State before call: State(args=[[], 'Test --language en --filter off'], kwargs={}, channel=None)
DEBUG 2016-05-04T16:14:15 Outgoing message (freenode): PRIVMSG #limnoria-bots :teward: No matches found.
```

**Comment by atirjavid** [comment]
Error: The Google Web Search API is no longer available. Please migrate to the Google Custom Search API (https://developers.google.com/custom-search/)

I believe it's because google has made some changes. The plugin needs a bit of a rewrite.

**Comment by teward** [comment]
@atirjavid Hate to ask you to check, but in the Testing branch, these two commits were made today in this order:

https://github.com/ProgVal/Limnoria/commit/b5268d63a3903abf7b7f3b69052b4dcfb24ec979
https://github.com/ProgVal/Limnoria/commit/f8aaddd5b5ffe440254236db3cbbe5277dc520b7

With these applied, it should supposedly "fix" the issue - and I don't think a custom search would apply in these cases, given the nature of how the "Google" module works?

And I know the API isn't working anymore - that's not the issue I'm reporting - I'm reporting that the changes that @ProgVal made today to 'fix' this don't actually fix it.

**Comment by ProgVal** [comment]
Does 6f1045e help?

**Comment by atirjavid** [comment]
That was my mistake. It wasn't on testing when I tested.

**Comment by ProgVal** [comment]
No, you tested it before I committed that fix

**Comment by teward** [comment]
@ProgVal Confirmed, the latest commit (6f1045e) appears to allow 'Google' to work once again.

**Comment by teward** [comment]
Fixed via https://github.com/ProgVal/Limnoria/commit/6f1045ed20bcb4b0ddc0b845c01cdbb886a91ccc
