### ISSUE TITLE
ShrinkUrl.expand is dead (longurl.org no longer resolves)

### ISSUE THREAD

**Issue by GLolol** [ProgVal/Limnoria#1243]
```
17:41 <~GL> `expand http://overdrivenetworks.com
17:41 <@Lily> ​Error: <urlopen error [Errno -2] Name or service not known>
```

Would it be better to have the bot resolve redirects itself instead of relying on a third-party service? I wrote [a small command-line app to do this](https://github.com/GLolol/codescraps/blob/master/utils/h.py) many months ago.

**Comment by ProgVal** [comment]
There is the Untiny plugin in my repo. For some reason I thought it was a good idea to use a third-party service…

**Comment by GLolol** [comment]
Should `expand` be removed from ShrinkUrl for now?
