### ISSUE TITLE
Selectable language for title snarfer

### ISSUE THREAD

**Issue by ProgVal** [ProgVal/Limnoria#1245]

**Comment by GLolol** [comment]
What does this entail exactly, out of curiosity? Isn't https://github.com/ProgVal/Limnoria/blob/master/plugins/Web/plugin.py#L182 already an internationalized string?

**Comment by ProgVal** [comment]
HTTP Accept-Language

**Comment by oddluck** [comment]
Isn't this config already covered in https://github.com/ProgVal/Limnoria/blob/master/src/conf.py#L1331 and https://github.com/ProgVal/Limnoria/blob/testing/plugins/Web/plugin.py#L152? I think this issue can be closed?

**Comment by jlu5** [comment]
This was fixed by #1399.
