### ISSUE TITLE
Documentation: Installing for Fedora / CentOS / RHEL / FreeBSD

### ISSUE THREAD

**Issue by jflory7** [ProgVal/Limnoria#1247]
Coming soon in both Fedora and EPEL repository (for CentOS and RHEL), `limnoria` will be an official package that can be installed with the distribution's package manager. The packages are currently in testing [here](https://bodhi.fedoraproject.org/updates/?packages=limnoria), but should be synced to the stable repositories by the end of the week.

I wasn't sure if this was a detail the Limnoria team might want to mention in the documentation to make it simpler for those wishing to use Limnoria on those distributions.

## Fedora

Once it is synced to the official repositories, it's one command to install.

`$ sudo dnf install limnoria`

## CentOS / RHEL

You have to first add the EPEL repository [[EL7](https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm)|[EL6](https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm)|[EL5](https://dl.fedoraproject.org/pub/epel/epel-release-latest-5.noarch.rpm)] before being able to install the package on CentOS / RHEL. Once you have, you can run the following command to install Limnoria.

`$ sudo yum install limnoria`

**Comment by ProgVal** [comment]
Great, thanks!
I'll add this to the doc shortly

**Comment by koobs** [comment]
FreeBSD has had a [Limnoria Port & Package](https://www.freshports.org/irc/py-limnoria/) since December 2015

Instructions for installation:

FreeBSD
--------

Port: `$ cd /usr/ports/irc/py-limnoria && sudo make install clean`
Package:  `$ sudo pkg install py27-limnoria`

**Comment by koobs** [comment]
@jflory7 Can you update the issue summary to include _FreeBSD_ please

**Comment by ProgVal** [comment]
@koobs Is there a Python 3 package? I would prefer not to promote a package that runs Limnoria on Python 2.

**Comment by koobs** [comment]
@ProgVal To clarify FreeBSD's current Python 2/3 capabilities:

* Ports can be built with any version of Python, as the user wants.
* _Official_ ackages are currently only built for the default python version, which is currently Python 2.7 but there is nothing stopping users from creating their own Python 3.x version of the package.
* I can create a py3-limnoria port, which defaults to Python 3.x, so both packages are built

Also, the tests pass perfectly (except for the non portable ping2 tests) on 2.7 so im confident in the quality, and while I understand your desire to want to promote only the latest, at an OS/Distribution level there are quite often (as in this case), many more options.

I'd appreciate it if you could add the instructions as provided, with the promise that I'll create a python 3.x version of the package and update the documentation when that's done.

**Comment by ProgVal** [comment]
> Ports can be built with any version of Python, as the user wants.

Can you give me some instructions I can copy-paste in the doc?

> I can create a py3-limnoria port, which defaults to Python 3.x, so both packages are built

That would be great.

**Comment by koobs** [comment]
@ProgVal Text updated

**Comment by ProgVal** [comment]
Also, I see that the port has a lot of py27-* dependencies. Won't that be a problem for people using PYTHON_VERSION=3.5? (Unused dependencies + actual dependencies not checked)

**Comment by koobs** [comment]
@ProgVal 

No minimum OS version. We don't have package branches per OS versions, but we do have two port branches (head/quarterly) from which packages are produced. At least all (currently supported) FreeBSD versions are supported for all ports/packages and QA'd for, otherwise it's a bug. I QA Limnoria on all versions and on Python 2.x/3.x.

No, DEFAULT_VERSIONS overrides the python version for dependencies as well. Easier way to think about it is that many packages (pyXY-foo) can be and are created from the same underlying port. It just so happens that only a single variant (py27-foo) is built by default (default being the operative word) on the official package cluster. Trust me, i

**Comment by koobs** [comment]
At some point in the near future, official FreeBSD packages will be produced for all Python versions supported in Ports (at the present time, 2.7, 3.3, 3.4, 3.5, with 3.6a3 about to land shortly). These (python and python packages) are all concurrently installable

**Comment by ProgVal** [comment]
ok!

Please tell me when py3-limnoria is available so I can update the doc.

**Comment by koobs** [comment]
@ProgVal  I'll provide with a PR, don't worry :)

**Comment by koobs** [comment]
@ProgVal Also `F` comes before `U` in the alphabet ;) </freebsd-troll>

**Comment by ProgVal** [comment]
The order is an arbitrary “what I feel Limnoria's users use most according to IRC discussions and also grouped by distributions family” (with a bias on Debian, I'll switch it with Ubuntu)
