### ISSUE TITLE
Improper URL encoding in (deprecated) Google plugin

### ISSUE THREAD

**Issue by polyzen** [ProgVal/Limnoria#1260]
For example:
> !ud carajo land
> Urban Dictionary: Carajo: <http://www.urbandictionary.com/define.php%3Fdefid%3D364880%26term%3DCarajo>
> !help ud
> (ud <an alias, 0 arguments>) -- Alias for "google site:http://www.urbandictionary.com $*".

This also occurs with a yt/youtube alias of the same sort.

Version:
> The current (running) version of this Limnoria is 2016.05.06, running on Python 3.5.2 (default, Jun 28 2016, 08:46:01)  [GCC 6.1.1 20160602].

**Comment by polyzen** [comment]
I had not mentioned this (as I haven't gotten a chance to test this), but thank you for the _very_ quick response.

**Comment by ProgVal** [comment]
:)
