### ISSUE TITLE
Channel-specific reply.oneToOne setting doesn't seem to work

### ISSUE THREAD

**Issue by GLolol** [ProgVal/Limnoria#1266]
Snippet from a channel:
```
18:52 <~GL> `config reply.onetoone
18:52 <@Lily> ​Global: True; #void: False
18:56 <~GL> `replies a b c
18:56 <@Lily> ​a, b, and c
```

It looks like https://github.com/ProgVal/Limnoria/commit/fc9daa9953ba7c1a83aa19fea37ac0d800ce67a5 was supposed to fix this by adding a `to=` option, but that doesn't seem to be used. If I eval `irc.replies(['a','b','c'], to='#void')` explicitly, only then does the channel-specific option begin to work.

**Comment by ProgVal** [comment]
wtf was that commit supposed to do

**Comment by ProgVal** [comment]
nevermind
