### ISSUE TITLE
Web: title — needs to be asynchronous

### ISSUE THREAD

**Issue by mpan-pl** [ProgVal/Limnoria#1275]
Running _title_ from _web_ on targets, that are not accessible but the network doesn’t drop connection immedietely on them, blocks Limnoria until a connection timeout is reached, causing reproducible DoS.

    <user> web title http://blackhole/
    … some time later …
    <bot>  <urlopen error [Errno 110] Connection timed out>

The query should be done asynchronously or with a short timeout.

**Comment by ProgVal** [comment]
Wow, I'm sorry for that regression in the last release.
I pushed a fix to the testing branch and will release soon.
