### ISSUE TITLE
log unknown numerics

### ISSUE THREAD

**Issue by Hello71** [ProgVal/Limnoria#1287]
this makes sense and also (mostly) remedies https://limnoria-doc.readthedocs.io/en/latest/use/faq.html#why-won-t-supybot-respond-to-private-messages. I ran supybot in console and even with `--debug` option it didn't print any warnings about not being able to send messages.

**Comment by ProgVal** [comment]
Limnoria already logs unknown numerics. For example:

```
ERROR 2017-03-27T15:00:47 supybot Unhandled error message from server: IrcMsg(prefix="irc.fc00.io", command="482", args=('Limnoria', '#cjdns', "You're not channel operator"))
```

**Comment by Hello71** [comment]
oh, freenode only sends errors for privmsgs to +R, not notices
