### ISSUE TITLE
Support for messages using STATUSMSG (+#channel, etc.)

### ISSUE THREAD

**Issue by phillid** [ProgVal/Limnoria#1291]
Sending a message to identify against a bot account, by sending to `+#channel` rather than plain `#channel` will not result in the usual message:

    Error: That operation cannot be done in a channel.

I have not tested with actual credentials, but it is my assumption that the bot will allow identification in-channel on the voice-only or op-only etc (sub-channels?). Testing with incorrect credentials afforded me this response from the bot:

    Error: Your hostmask doesn't match or your password is wrong.

hinting that the bot would allow me to successfully identify in-channel if I was foolhardy enough to use my real credentials.

This poses the same security issue that causes plain in-channel identification to be blocked.

**Comment by ProgVal** [comment]
Hi,

Sorry for not replying earlier. Here are a few thoughts from IRC:

```
<pinkieval> I do not know what to do with this https://github.com/ProgVal/Limnoria/issues/1291
<pinkieval> +#channel is not standard
<d> non-standard but rather widely supported.
<pinkieval> what if there is a network that allows nicks starting with a +?
<pinkieval> sending @identify to +#channel is accidental and, I believe, rare enough to be ignored
<pinkieval> but if you can't use @identify at all if the bot's nick starts with a +, it would be quite an inconveniance
<pinkieval> we're 100% in non-standardized territory here, and I don't know much about all the weirdness of weird IRC networks
<d> I think at least most major IRC networks run IRCds with the prefix support.  Like e.g. freenode.
<d> But yeah, it's one of those annoyances...
```

Any opinions on that?

**Comment by GLolol** [comment]
AFAIK 005 responses send whether prefixed messages are supported, via the `STATUSMSG` key. On freenode this shows as `STATUSMSG=@+`, for example.

I don't think any sane IRCd would allow a channel prefix to conflict with a nick character - that'd really confuse any `/names` parsers because users are literally sent in the form `user1 @user2 +user3`. So, I'd say that stripping the channel prefixes and re-adding them to the response is safe enough. That said, I don't really know of any bot framework that actually parses prefixed messages.

**Comment by ProgVal** [comment]
Ah! `STATUSMSG` looks good.

**Comment by phillid** [comment]
@ProgVal You do raise a good point that it is very rare.

Actually, after having some time to reflect, I suppose denying identification in-channel is futile anyway. If someone tried to do it, they have just broadcast their password anyway, so denying it in any case is sort of moot.

**Comment by ProgVal** [comment]
There is work in progress to solve this, in a specific branch: https://github.com/ProgVal/Limnoria/compare/testing...netconf-and-ircmsgs-channel

Don't expect it to be released before the end of the year though, because I want to test it thoroughly.

**Comment by ProgVal** [comment]
Branch is now merged and released.
