### ISSUE TITLE
Unloading plugins using lowercase form adds duplicate entries to supybot.plugins

### ISSUE THREAD

**Issue by parkerbryan** [ProgVal/Limnoria#1295]
Limnoria version 2017.03.31, running on Python 3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170118]

If I unload a plugin using lowercase form ('unload plugin' instead of 'unload Plugin'), it adds a duplicate entry of 'plugin' to supybot.plugins while 'Plugin' still exists in the same variable.

**Comment by GLolol** [comment]
Confirming as I've noticed this behaviour too.
