### ISSUE TITLE
config supybot.commands.allowShell true suggests using commands with @ prefix

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1307]
> `Error: This configuration variable is not writeable via IRC. To change it you have to: 1) use @flush 2) edit the config file 3) use @config reload.`

As far as I can see, naming `@` prefix is inconsistent and isn't used anywhere else in Limnoria. For example:

> `(scheduler add <seconds> <command>) -- Schedules the command string <command> to run <seconds> seconds in the future. For example, 'scheduler add [seconds 30m] "echo [cpu]"' will schedule the command "cpu" to be sent to the channel the schedule add command was given in (with no prefixed nick, a consequence of using echo). Do pay attention to the quotes in that example.`

* https://github.com/ProgVal/Limnoria/blob/master-2017-10-25/plugins/Scheduler/plugin.py#L136-L140

**Comment by GLolol** [comment]
Fixed by #1308
