### ISSUE TITLE
supybot.externalIP doesn't appear to be used

### ISSUE THREAD

**Issue by GLolol** [ProgVal/Limnoria#1311]
https://github.com/ProgVal/Limnoria/search?utf8=%E2%9C%93&q=externalIP&type= shows no hits other than [the config entry](https://github.com/ProgVal/Limnoria/blob/testing/src/conf.py#L1281-L1284). Leaving this variable in seems misleading as the actual bindhost settings used are `supybot.protocols.irc.vhost(v6)` for IRC and `supybot.servers.http.hosts(4|6)` for the HTTP server.

**Comment by ProgVal** [comment]
Indeed.

**Comment by ProgVal** [comment]
There used to be (before 2005) a DCC plugin that used it.

**Comment by GLolol** [comment]
@ProgVal Should I mark this variable as deprecated or just "used by only external plugins"?

**Comment by ProgVal** [comment]
second option would be nice
