### ISSUE TITLE
HTTP server: how to start/use?

### ISSUE THREAD

**Issue by kierun** [ProgVal/Limnoria#1331]
I read the documentation and the wiki but either I was blind and could not find anything or the information as to how to start the HTTP server is not there. I have set up an nginx proxy but that shows nothing.

Any kind soul could point me in the right direction?

Thanks.

**Comment by ProgVal** [comment]
Hi. Did you see this page? https://limnoria.readthedocs.io/en/latest/use/httpserver.html

**Comment by kierun** [comment]
Yes, I did. Either I am dense (quit possibly) or this only talks about how to configure the bot and nginx (or Apache). How does the end localhost:8080 get created?

Or maybe I should say that I have configured http and nginx as above but the nginx proxy does not find anything to talk to.

**Comment by ProgVal** [comment]
You need to load a plugin that uses the HTTP server for the server to start. Or you could set `supybot.servers.http.keepAlive` to True (but you would only get a useless server).

**Comment by kierun** [comment]
`supybot.servers.http.keepAlive = True` is what I needed to get it working. However, I am now seeing "No plugins available." Does the ChannelLogger one not have one?… Hum, I'll investigate some more. Thank you for taking the time to help.

**Comment by ProgVal** [comment]
No, ChannelLogger only logs to files. However, you can set up nginx or apache2 to serve those files.

**Comment by kierun** [comment]
Yes, that's want I am planning on doing. Thank you.
