### ISSUE TITLE
Bot quitting with a odd error I’ve never seen.

### ISSUE THREAD

**Issue by TheDetectiveTaco** [ProgVal/Limnoria#1337]
My bot keeps stopping a minute or two after it starts and there was this error when it starts. https://www.irccloud.com/pastebin/P72saLEu

It quits on Freenode with Remote Host Closed The connection for the quit message. But on Aerospacechat with the TLS connection was non-properly terminated as the quit message? Any ideas?

**Comment by TheDetectiveTaco** [comment]
@ProgVal I removed that network from the networks the bot should connect to in the config file but it still quit on freenode with remote host closed the connection. But it’s probably because LinkRelay couldn’t find the other network because I told it not to connect to it.

**Comment by ProgVal** [comment]
LinkRelay shouldn't make the bot disconnect.

What do the logs tell you about the disconnection from freenode?

**Comment by TheDetectiveTaco** [comment]
Nothing this is what happens before it disconnects.

https://www.irccloud.com/pastebin/ogjmiTbn

**Comment by TheDetectiveTaco** [comment]
The server admin also said to make it handle it as a RAW numeric instead of a cmd. I’m not too sure how to do that.

**Comment by ProgVal** [comment]
Could you provide more lines from the logs?

Also set the log level (`supybot.log.level` or `supybot.log.stdout.level`) to `DEBUG`

**Comment by TheDetectiveTaco** [comment]
Sorry it may be all over the place I copied it on my phone.

https://www.irccloud.com/pastebin/S29JEpLu

**Comment by TheDetectiveTaco** [comment]
Here are the debug logs @ProgVal 

https://www.irccloud.com/pastebin/xGK8P6WO

**Comment by ProgVal** [comment]
It's not in debug mode. And I can't see any disconnect in this paste

**Comment by TheDetectiveTaco** [comment]
https://www.irccloud.com/pastebin/7XwhvgRP Here is before it quit 
And heres something that doesn’t really look right to me https://www.irccloud.com/pastebin/n0SUcbaX

**Comment by ProgVal** [comment]
These logs are completely normal.
But they are just after the bot connects, not before/while it disconnects

**Comment by TheDetectiveTaco** [comment]
the disconnect part is not at the bottom? It does not log from top down? Because that’s the end of the file I believe.

**Comment by ProgVal** [comment]
Yes, it logs from top down.

The disconnect is probably just before the connection at the beginning of your pastes

**Comment by TheDetectiveTaco** [comment]
https://i.imgur.com/r4lenAk.jpg

**Comment by TheDetectiveTaco** [comment]
I’ll try to get you the full logs when I get home in 3 hours or so.

**Comment by TheDetectiveTaco** [comment]
@ProgVal https://pastebin.com/WCRVXZ6s
Here is the debug.

**Comment by GLolol** [comment]
That still is not a full debug log - it is only the first few lines. Can you download the full messages.log to your system and send it to us? Please do so privately (e.g. by sending a link to us on IRC) if it contains login passwords or sensitive data you wouldn't want to disclose in public.

**Comment by TheDetectiveTaco** [comment]
Oh I must have missed the copy button here is the full debug log. https://pastebin.com/3SNXdK2P

**Comment by GLolol** [comment]
For reference, that error message seems to be from InspIRCd's antibear module: https://github.com/inspircd/inspircd-extras/blob/master/2.0/m_antibear.cpp#L78-L80. The error is logged because there's no explicit handling for numeric 439 ([which itself seems a questionable choice for connect announcements](http://defs.ircdocs.horse/defs/numerics.html#err-targettoofast-439)), but receiving it shouldn't be fatal [upon looking at Limnoria's code](https://github.com/ProgVal/Limnoria/blob/master/src/irclib.py#L911-L916). In other words, I think that error message is a red herring for any disconnect issues specifically.

Regarding the original issue, I don't see anything disconnect-related in that log either (the bot still logs outgoing messages to AerospaceChat after seeing the 439?)

**Comment by TheDetectiveTaco** [comment]
Yes, but only like a minute or two after it connects, sometimes less than a minute.

**Comment by ProgVal** [comment]
@TheDetectiveTaco Could you provide a log that starts well **before** the disconnect, and ends **after** the disconnect?
That's the only way we can help you

**Comment by TheDetectiveTaco** [comment]
@progv

**Comment by TheDetectiveTaco** [comment]
@ProgVal Oops, but that is the log when the bot is started until it disconnects, in the console when you start the bot it just says killed. But it doesn’t actually say any of that in the messages.log file.

**Comment by ProgVal** [comment]
"Killed" means your OS (probably the oomkiller) killed it. It's not a bug in Limnoria.

**Comment by TheDetectiveTaco** [comment]
@progval it was a plugin I had loaded that was eating the CPU and it wasn’t a need so I just disabled it.
