### ISSUE TITLE
RSS plugin doesn't properly parse italic on title

### ISSUE THREAD

**Issue by TheMythPT** [ProgVal/Limnoria#1341]
Everytime an RSS feed as italic text on its title, the bot outputs  `somethind <i>italic</i> something`.
Would be perhaps better to make it ignore italic text.

**Comment by ProgVal** [comment]
Could you give me an example of such a feed?

**Comment by ProgVal** [comment]
The issue comes from the feed, not Limnoria. It escapes the `<i>` as `&lt;i&gt;`, specifically telling RSS readers not to interpret it as italic. It has the same issue with images (`<img>`)

**Comment by jlu5** [comment]
@ProgVal I think this is a wontfix then?

**Comment by ProgVal** [comment]
yeah
