### ISSUE TITLE
protocols.http.proxy occassionally gets ignored

### ISSUE THREAD

**Issue by Mikaela** [progval/Limnoria#1349]
I have `protocols.http.proxy` set to `127.0.0.1:8118` which is Privoxy listening on 127.0.0.1 and it's configured to send traffic to Tor (`forward-socks5t / 127.0.0.1:9050 .`).

However often `web fetch https://icanhazip.com/` returns the real IP\n and `web title http://expyuzz4wqqyqhjn.onion/` (www.torproject.org, see [onion.torproject.org](https://onion.torproject.org)) returns `<urlopen error [Errno -2] Name or service not known>`.

I have confirmed that the issue is not in Privoxy configuration as `curl -x http://127.0.0.1:8118 https://icanhazip.com` returns IP of a Tor exit node.

* The current (running) version of this Limnoria is 2018.09.01, running on Python 3.6.5 (default, Apr  1 2018, 05:46:30)  [GCC 7.3.0].
* Ubuntu 18.04.1 LTS

**Comment by Mikaela** [comment]
There was a suggestion that I may have a prescription error on it working sometimes and there were two interesting links.

* https://github.com/oddluck/limnoria-plugins/commit/a5dcd83d7bf4320c2c1d483b4d1d8b83b520c48a - SpiffyTitles commit adding support for HTTP proxy where the word "proxy" can be easily seen.
* https://github.com/ProgVal/Limnoria/blob/5195ff8e122c2966fc7c65dd16edc50a57a79232/plugins/Web/plugin.py - the Web plugin source code as it currently is doesn't mention the word "proxy" hinting that the plugin may not have proxy support at all?

**Comment by ProgVal** [comment]
> the Web plugin source code as it currently is doesn't mention the word "proxy"

it doesn't need to deal with proxies because it uses supybot.utils.web.

**Comment by Mikaela** [comment]
It seems to hardcode the proxy as `None` instead of actually reading the configured proxy?

* https://github.com/ProgVal/Limnoria/blob/master-2021-06-17/src/utils/web.py#L128

**Comment by ProgVal** [comment]
Yes, but it's overridden here: https://github.com/ProgVal/Limnoria/blob/67a39a3adbd78d8088a0bac94c47227891a54e58/src/conf.py#L1335

**Comment by BlankEclair** [comment]
This is caused by upkeep:
```
[22/10/2024 17:57] --> BlankEclairBot (~limnoria@user/BlankEclairBot) has joined this channel.
[22/10/2024 17:57] *** ChanServ sets mode: +v BlankEclairBot
[22/10/2024 17:58] <BlankEclair> .config supybot.protocols.http.proxy
[22/10/2024 17:58] <BlankEclairBot> localhost:9050
[22/10/2024 17:58] <BlankEclair> .title https://check.torproject.org/
[22/10/2024 17:58] <BlankEclairBot> Error: That URL raised <<urlopen error Tunnel connection failed: 501 Tor is not an HTTP Proxy>>
[22/10/2024 17:58] <BlankEclair> .upkeep
[22/10/2024 17:58] <BlankEclairBot> 884 objects collected.
[22/10/2024 17:58] <BlankEclair> .title https://check.torproject.org/
[22/10/2024 17:58] <BlankEclairBot> Error: That URL raised <<urlopen error timed out>>
```

(It timed out for the second command because I configured my network so that Limnoria can only access localhost)

**Comment by progval** [comment]
Good catch, thank you.

**Comment by BlankEclair** [comment]
I believe this is the cause:
* When upkeep is being executed, it runs the flushers:
  https://github.com/progval/Limnoria/blob/246f4d3e626cdbb1d744ba9c4e06c704d8c30a95/src/world.py#L148-L150
* In the main limnoria script, it registers a flusher that saves the registry to disk:
  https://github.com/progval/Limnoria/blob/246f4d3e626cdbb1d744ba9c4e06c704d8c30a95/src/scripts/limnoria.py#L243-L252
* When saving the registry to disk, the code instantiates the class with its default value to print it out in the file:
  https://github.com/progval/Limnoria/blob/246f4d3e626cdbb1d744ba9c4e06c704d8c30a95/src/registry.py#L149-L159
* Instantiating the class calls `setValue()` by default:
  https://github.com/progval/Limnoria/blob/246f4d3e626cdbb1d744ba9c4e06c704d8c30a95/src/registry.py#L347-L348
* supybot.protocols.http.proxy uses a custom type that changes global state when `setValue()` is called:
  https://github.com/progval/Limnoria/blob/246f4d3e626cdbb1d744ba9c4e06c704d8c30a95/src/conf.py#L1416-L1432
