### ISSUE TITLE
[regression] Network whois claims nicks beginning with number don't exist

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1350]
*Originally reported as #312 and fixed by https://github.com/ProgVal/Limnoria/commit/570e30f1b7cbba865188ef326872693125fda747*

```
__network whois 7IZAAOTHJ 
There is no user 7izaaothj on freenode.
```

> The current (running) version of this Limnoria is 2018.09.01, running on Python 3.6.6 (default, Sep 12 2018, 18:26:19)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]].  The newest versions available online are 2018.09.09 (in master), 2018.10.14 (in testing).

While nick 7IZAAOTHJ is on the same channel as the bot. Other examples from #freenode (at time of writing): 17WAAUPXA 32NAAER3J

**Comment by jlu5** [comment]
This seems to be a weird edge case in freenode's IRCd. If I run `/raw whois 32NAA4AP6 32NAA4AP6` (taking a random UID nick from #freenode), the command runs successfully. But `/raw whois 32naa4ap6 32naa4ap6` fails with `* 32naa4ap6 :No such nick/channel`.

For reasons unclear to me, Limnoria lowercases nicks before sending a whois, and the IRCd is handling this case differently:
https://github.com/ProgVal/Limnoria/blob/master-2019-09-08/plugins/Network/plugin.py#L220-L232
