### ISSUE TITLE
networks.NETWORK.servers uses IPv6:port instead of [IPv6]:port

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1352]
I wanted to connect my bot to a network over [Yggdrasil](https://yggdrasil-network.github.io). In it all hosts are IPv6 addresses from `0200::/7` and as I don't want to rely on DNS I attempted two syntaxes:

* `[201:677d:1809:c5eb:202a:d39:e598:305]:6697` which I think to be the standard as it works on web browsers and everything else
* `201:677d:1809:c5eb:202a:d39:e598:305:6697` which actually worked, but I think it's not clear at first glance which is the port here.  I have also seen IPv6 addresses ending to `:6667`.

> The current (running) version of this Limnoria is 2018.09.09, running on Python 3.6.6 (default, Sep 12 2018, 18:26:19)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]].  I couldn't fetch the newest version from the Limnoria repository.

* * * * *

*This issue is a potential duplicate of https://github.com/ProgVal/Limnoria/issues/1329, but that is somewhat unclear, so I am not entirely sure.*

**Comment by ProgVal** [comment]
Though I agree supporting the `[addr]:port` syntax as well would be nice

**Comment by ProgVal** [comment]
Fixed by #1361 1361
