### ISSUE TITLE
Tracking third-party Python3-incompatible plugins

### ISSUE THREAD

**Issue by cottongin** [progval/Limnoria#1354]
With Python2 EOL approaching and [deprecation warnings](https://github.com/ProgVal/Limnoria/commit/46935370557937f1c2c91234b18e2beac3276e94) added to Limnoria, I thought having one place to keep track of any incompatible third-party plugins would keep things easier to find and fix.

Ideally Issues would be submitted individually to those projects' but this may help shed light on abandoned projects and give contributors an idea for things to upgrade or fix.

**EDIT: Limnoria removed Python <3.4 support on 2020-01-01**

**Comment by cottongin** [comment]
**Not working:**
[limnoria-tvmaze](https://github.com/Znuff/limnoria-tvmaze)

**Python 3 rewrite (by me) in progress here:**
[TVMaze](https://gitlab.com/cottongin/TVMaze)

**Comment by loljoho** [comment]
**Not working:**
[TriviaTime](https://github.com/tannn/TriviaTime)

**Python 3 rewrite:** (credit goes to @oddluck)
[TriviaTime](https://github.com/oddluck/TriviaTime)

**Comment by oddluck** [comment]
**Not working:**
[Uno](https://github.com/SpiderDave/spidey-supybot-plugins/tree/master/Plugins/Uno)

**Python 3, working:**
[Uno](https://github.com/oddluck/spidey-supybot-plugins/tree/master/Plugins/Uno)

**Comment by IotaSpencer** [comment]
I can work on a few if someone wants to give me a list
My plugins are at [IotaSpencer/supyplugins](/IotaSpencer/supyplugins)

**Comment by Znuff** [comment]
> **Not working:**
> [limnoria-tvmaze](https://github.com/Znuff/limnoria-tvmaze)
> 
> **Python 3 rewrite (by me) in progress here:**
> [TVMaze](https://gitlab.com/cottongin/TVMaze)

You know, I do accept pull-requests...

**Comment by Mikaela** [comment]
Keeping me running a Python 2 bot: [meetingology](https://bazaar.launchpad.net/~ubuntu-bots/ubuntu-bots/meetingology/changes).

**Comment by skeeloco** [comment]
I think pretty much everything is not working with Python3. I had to switch my bot to use 3 because there's a new weather plugin out there that only works with 3 and every other plugin broke on me. Are there any plans to update plugins at all or is Limnoria dead? I'm mostly just concered about the RSS plugin and maybe a stock/ crypto plugin.

**Comment by ProgVal** [comment]
The RSS plugin works with Python 3 (as well as all other plugins provided with Limnoria). Please list here other plugins that don't work with Python 3

**Comment by djlolito** [comment]
Hello the GitHub plugin - dont work , says Error: This plugin may be incompatible with your current Python version. Try running 2to3 on it. , https://github.com/blast007/supybot-github
