### ISSUE TITLE
Idea: Disable last command per channel

### ISSUE THREAD

**Issue by traumschule** [ProgVal/Limnoria#1356]
[From the code](https://github.com/ProgVal/Limnoria/blob/master/plugins/Misc/plugin.py#L411) it looks there's no possibility to disable the `last` command per channel, or to to enable it only for selected ones, for example with
> config channel #channel supybot.plugins.misc.last.enable
or
> config channel #channel supybot.plugins.misc.last.disable

**Comment by ProgVal** [comment]
Hi,

Sorry for not replying earlier, I missed the notification.

Limnoria's capabilities system allows for disabling any command per channel: `@channel capability set #channelname -Misc.last`
