### ISSUE TITLE
[RSS] Add option to shorten URL's via Bitly or any order service

### ISSUE THREAD

**Issue by TheMythPT** [ProgVal/Limnoria#1358]
This would help when these are long URLs like atom feeds from GitHub projects commits

**Comment by jlu5** [comment]
The ShrinkUrl plugin provides the ability to do this, see `config help plugins.shrinkurl.outfilter`

> Determines whether the bot will shrink the URLs of outgoing messages if those URLs are longer than 
> supybot.plugins.ShrinkUrl.minimumLength.  (Current value: False)

We don't support bit.ly in particular since it requires an API key, but there are other services which do the same thing.
