### ISSUE TITLE
How do I reload a plugin

### ISSUE THREAD

**Issue by wodim** [ProgVal/Limnoria#1363]
I'm not 100 % sure but I think back in the day "unload $1; load $1" worked. But now it doesn't seem to work; if I modify a plugin and then do that the old code is executed. I have to restart the whole bot to modify a plugin. Is there any workaround to this?

**Comment by ProgVal** [comment]
There is the "reload" command, it works just like "load".

If your plugin imports other files and you modify these files, modifications are ignored because Python "caches" modules. You can bypass this cache by reloading them:

```
from imp import reload
import my_module

reload(my_module)
```

**Comment by wodim** [comment]
Thanks, I'll take a look at your suggestions.
