### ISSUE TITLE
IRC connection dying due to uncaught exception

### ISSUE THREAD

**Issue by badnetmask** [ProgVal/Limnoria#1364]
My bot dies every once in a while with this message:

ERROR 2019-03-26T15:43:15 supybot Uncaught exception in in drivers.run:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/supybot/drivers/__init__.py", line 104, in run
    driver.run()
  File "/usr/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 195, in run
    self._select()
  File "/usr/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 171, in _select
    instance._read()
  File "/usr/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 222, in _read
    self._sendIfMsgs()
  File "/usr/lib/python2.7/site-packages/supybot/drivers/Socket.py", line 135, in _sendIfMsgs
    self.outbuffer += ''.join(map(str, msgs))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 130: ordinal not in range(128)
ERROR 2019-03-26T15:43:15 supybot Exception id: 0xd0be9
INFO 2019-03-26T15:43:15 supybot Removing driver SocketDriver(Irc object for IrcServer).
INFO 2019-03-26T16:14:00 supybot Flushers flushed and garbage collected.

Apparently there has been a different bug related to mishandling of UTF-8 characters.
https://github.com/ProgVal/Limnoria/issues/1230

I'm wondering if this is the same type of problem, just in a different situation.

**Comment by ProgVal** [comment]
Hi, could you send the list of loaded plugins of your bot?

**Comment by badnetmask** [comment]
Admin, AutoMode, Channel, ChannelStats, Config, Figlet, Games, Karma, Markov, Math, Misc, Network, NickCapture, NotifyHTTP, Owner, Personality, Praise, Quote, Scheduler, Shift, Status, StockPrice, and User.

**Comment by ProgVal** [comment]
I can't find NotifyHTTP, Personality, or Shift. Could you send me a link to their source code?

**Comment by badnetmask** [comment]
I don't recall where we pulled them from. They're part of our customization.

**Comment by ProgVal** [comment]
Could run `egrep "irc\.(queue|send)Msg` on these plugins and show me the results? (Also Markov, Figlet, and Stock in case I didn't look at the same ones as the ones you have)

**Comment by badnetmask** [comment]
NotifyHTTP/plugin.py:                    irc.queueMsg(msg)
Shift/plugin.py:        irc.queueMsg(msg)
Shift/plugin.py:            irc.queueMsg(f(nicks[i:i + numModes]))

**Comment by ProgVal** [comment]
Could you send the content of `NotifyHTTP/plugin.py` and `Shift/plugin.py`? You can use the email address in my profile if you don't want them to be public

**Comment by ProgVal** [comment]
If not, could you re-run grep with `-C 10`? It may be harder to diagnose but I'll try.

**Comment by badnetmask** [comment]
I realized we had to apply a patch to the supybot code to fix a compatibility problem with a given IRC server. I wonder if this is what may be causing the problem.

`sed -i "s/from __future__ import division/from __future__ import division\nfrom __future__ import unicode_literals/" /usr/lib/python2.7/site-packages/supybot/drivers/Socket.py`

**Comment by ProgVal** [comment]
Yes, this is the cause.

What was the problem with the IRC server?

**Comment by badnetmask** [comment]
I honestly do not remember what the problem was. This was a long time ago. I would hope that showing the change would ring a bell.
Since this sounds like self-inflicting problem, I think it doesn't make sense to keep chasing this bug.
Thank you.
