### ISSUE TITLE
google search regex doesn't match results

### ISSUE THREAD

**Issue by horstderheld** [ProgVal/Limnoria#1365]
Google changed the website a bit and now the google search plugin doesn't match any result.

**Comment by ProgVal** [comment]
ooh this is going to be a fun one

**Comment by ProgVal** [comment]
I just pushed a fix to the `testing` branch, so the patch will be part of the next release.

If you want something more stable, I recommend you switch to a third-party plugin. See https://github.com/ProgVal/Limnoria/blob/master/plugins/Google/plugin.py#L100-L106

**Comment by horstderheld** [comment]
Well, there we go again, maybe it's time to remove this plugin.

**Comment by ProgVal** [comment]
Try this: dba0ae3771f4c1bedf487157e1060c7f848d025f
