### ISSUE TITLE
format title command gives incorrect output

### ISSUE THREAD

**Issue by japanoise** [ProgVal/Limnoria#1366]
The letter after an apostrophe is erroneously capitalised:

```
12:54 <japanoise> %format title It's an older code sir, but it checks out
12:54 <@NiGHTS> It'S An Older Code Sir, But It Checks Out
12:54 <japanoise> Should be "It's An Older Code Sir, But It Checks Out"
```

**Comment by jlu5** [comment]
This isn't really a Limnoria bug, it's just how title case is defined in Python: https://docs.python.org/3/library/stdtypes.html#str.title

**Comment by ProgVal** [comment]
though we could use the workaround mentioned there
