### ISSUE TITLE
MoobotFactoids.test.FactoidsTestCase.testMost failure

### ISSUE THREAD

**Issue by mapreri** [ProgVal/Limnoria#1383]
In Debian we have been seeing this error since some weeks.  The only relevant change looks like the move from Perl 5.28 to 5.30, but I can't imagine why…

```
======================================================================
FAIL: testMost (MoobotFactoids.test.FactoidsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/supybot/test.py", line 192, in runTest
    originalRunTest()
  File "/usr/lib/python3/dist-packages/supybot/plugins/MoobotFactoids/test.py", line 228, in testMost
    'Most prolific authors:.*moo.*(1).*boo.*(1)')
  File "/usr/lib/python3/dist-packages/supybot/test.py", line 380, in assertRegexp
    '%r does not match %r' % (m.args[1], regexp))
AssertionError: None is not true : 'Most prolific authors: boo (1) and moo (1)' does not match 'Most prolific authors:.*moo.*(1).*boo.*(1)'
```

It took me quite a while to spot it, but the order of "boo" and "moo" changed (`boo and moo` vs `moo and boo`).  I don't know where that sentence is coming from, so I can't figure if it was supposed to be changed.  Can you shed some light on me here?

Would you happen to have any clue what might be up with that?

While looking at this, I noticed that the test file has is dealing with regexes, quite a few using `(` in the regex string.  I recommend you start using r-strings, and escape the `(`s.

**Comment by ProgVal** [comment]
I would guess that sqlite now changes the order of author records (which is totally valid), so the test's regexp should be updated to support both orders.

**Comment by mapreri** [comment]
in which case, I recommend

```r'Most prolific authors:.*(b|m)oo.*\(1\).*(b|m)oo.*\(1\)'```

**Comment by mapreri** [comment]
Incidentally, indeed, the first failing test changed the version of sqlite3:
```
-libsqlite3-0	3.29.0-2
+libsqlite3-0	3.30.0-1
```
