### ISSUE TITLE
config network reply.withnotice False appears to have no effect

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#1393]
I have tried issuing `config network reply.withnotice False` and `config network pirateirc reply.withnotice False` in private and on channel, but I regardless keep getting the success and pongs as NOTICEs.

* > The current (running) version of this Limnoria is 2019.11.22, running on Python 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0].  The newest versions available online are 2019.11.22 (in master), 2019.11.27 (in testing).
* Ubuntu 18.04.3 LTS

I wouldn't generally be attempting to get PRIVMSGs out, but I am hoping to workaround https://github.com/42wim/matterbridge/issues/754 on PirateIRC.

**Comment by ProgVal** [comment]
Oh, there's a bunch of config variables related to replies that I missed when making variables network-specific.

If it's not too pressing, I'll deal with it later in the week

**Comment by Mikaela** [comment]
:+1: no hurry from my side

**Comment by Mikaela** [comment]
Thanks, it's working :)
