### ISSUE TITLE
Limnoria documentation uses the wrong cert

### ISSUE THREAD

**Issue by cjbayliss** [ProgVal/Limnoria#1406]
if you browse to https://limnoria.readthedocs.io/ it redirects to https://doc.supybot.aperio.fr/en/latest/ which results in Firefox displaying a warning page because https://doc.supybot.aperio.fr/en/latest/ is using the cert for readthedocs.io

```
Web sites prove their identity via certificates. Firefox does not
trust this site because it uses a certificate that is not valid
for doc.supybot.aperio.fr. The certificate is only valid for the
following names: *.readthedocs.org, readthedocs.org

Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

**Comment by ProgVal** [comment]
it redirects me to http://doc.supybot.aperio.fr/en/latest/ (not HTTPS), not sure why you get the HTTPS page.
But I should definitely fix this.

**Comment by ProgVal** [comment]
I moved the docs to https://docs.limnoria.net/ and am now self-hosting it; so this issue is solved.
