### ISSUE TITLE
Output of scheduler is omitted when called via Utilities:ignore

### ISSUE THREAD

**Issue by qwertfisch** [progval/Limnoria#1408]
The goal is to sequence multiple commands which are (in this case) called at different times via scheduler. The command executed is an `echo` (or `reply`) command. But when doing this via `Utilities:ignore`, no message is displayed.

## Example
`utilities ignore [sched add 1 echo First] [sched add 5 echo Second]`

## Expected result
Expected is that the scheduler commands are run, and that after 1 second the echo command is executed, respectively after five seconds the second command. The output of both executed commands (the `echo`s) should be visible.

## Actual result
The commands are indeed run at the given time, but the echo output is omitted. From the definition of `ignore` it is expected that any direct output of `sched` is omitted, but the output of the _executed_ command should not be affected.

A previous instance of SupyBot did as expected from the example.

**Comment by ProgVal** [comment]
This is probably caused by 543edccd416f5a45b2a2ee2cc6218264d220bc49. I'm not sure if this should be considered a bug.

What about this, as a workaround? `utilities last [sched add 1 echo First] [sched add 5 echo Second] [utilities ignore]`

**Comment by qwertfisch** [comment]
It seems the issue was premature. After updating to a newer version of Limnoria, the output is now as expected. Possibly the `Scheduler` plugin was not working correctly.
