### ISSUE TITLE
failed to get channel specific value of supybot.reply.mores.length

### ISSUE THREAD

**Issue by PaddyFrank** [ProgVal/Limnoria#1409]
I use L from the testing branch per 2020-05-15 on freenode. I only used it in query with a few "list" commands, then let it rest over night and in the morning the log was full of these messages:

WARNING 2020-05-16T06:11:05 Trying to get channel-specific value of supybot.reply.mores.length for channel Mother, but it is not a channel. This is a bug, please report it.

**Comment by ProgVal** [comment]
Ugh. Yeah right, I think I'll just silence this warning, it's pointless

**Comment by ProgVal** [comment]
"Fixed", just upgrade and restart to get rid of this warning.
