### ISSUE TITLE
in supybot-wizard: AttributeError: 'int' object has no attribute 'id'

### ISSUE THREAD

**Issue by inhahe** [ProgVal/Limnoria#1410]
python 3.7 64-bit
limnoria-2020.4.11
windows 10

in supybot-wizard:

------------------

What should the owner's username be? inhahe

That user already exists, and has owner capabilities already.
Perhaps you added it before?

Do you want to remove its owner capability? [y/n] (default: n) y

Traceback (most recent call last):
  File "supybot-wizard", line 782, in <module>
    main()
  File "supybot-wizard", line 637, in main
    ircdb.users.setUser(id, u)
  File "C:\Miniconda3\lib\site-packages\supybot\ircdb.py", line 786, in setUser
    self.nextId = max(self.nextId, user.id)
AttributeError: 'int' object has no attribute 'id'

**Comment by ProgVal** [comment]
It looks like this bug is at least 15 years old! It will be fixed in the next release, thanks for the report.

btw, if you want to change the capabilities of a user, you should use `supybot-adduser` or edit `conf/users.conf`, it's faster than running the wizard and doesn't overwrite your config.

**Comment by inhahe** [comment]
thanks. i was actually trying to start over from scratch when I ran supybot-wizard, but somehow it knew I was inhahe. not sure why I wasn't owner.

**Comment by ProgVal** [comment]
supybot-wizard reuses some config files if they already exist, especially `conf/users.conf`. And according to the output, you were already owner, and it offered you to remove the owner capability
