### ISSUE TITLE
AttributeError: module 'supybot.i18n' has no attribute 'getLocaleFromRegistryFilename'

### ISSUE THREAD

**Issue by sacredland** [ProgVal/Limnoria#1428]
All done! Your new bot configuration is ./corona.conf. If you're
running a *nix based OS, you can probably start your bot with the
command line "supybot ./corona.conf". If you're not running a
*nix or similar machine, you'll just have to start it like you
start all your other Python scripts.

corona@nullroute:~/corona$ supybot ./corona.conf
Traceback (most recent call last):
  File "/usr/bin/supybot", line 216, in <module>
    i18n.getLocaleFromRegistryFilename(registryFilename)
AttributeError: module 'supybot.i18n' has no attribute 'getLocaleFromRegistryFilename'

**Comment by ProgVal** [comment]
Hi,

This means you have two versions of Limnoria installed at the same time. `/usr/bin/supybot` is from an old version, and you can find the location of the newer version with this command: `python3 -c "import os, supybot; print(os.path.dirname(supybot.__file__))"`

You'll need to uninstall one of them.
