### ISSUE TITLE
Configurable string for sedregex-plugin responses per channel

### ISSUE THREAD

**Issue by fred0r** [progval/Limnoria#1433]
it would be nice to be able to alter the 'static introduction' per chan from sedregex-plugin, since i want to conf different phrases/langs instead of 'meant to say' per #chan

**Comment by afwn90cj93201nixr2e1re** [comment]
@fred0rdou you have any contacts? Like skype or smthng like that?

**Comment by afwn90cj93201nixr2e1re** [comment]
@fred0r do you have any contacts? Like skype or smthng like that?

**Comment by fred0r** [comment]
nice - thx!
