### ISSUE TITLE
GPG unknown key

### ISSUE THREAD

**Issue by nolash** [ProgVal/Limnoria#1436]
Getting `Error: Unknown GPG key` when bot retrieves url with signature. The documentation looks off as to commands to use for the plugin, it says:

`+gpg gettoken...`

whereas I have to write

`gpg signing gettoken ...`

Using the pypi version;

```
Limnoria 2020.10.10 running on Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0]
```

**Comment by ProgVal** [comment]
> Getting `Error: Unknown GPG key` when bot retrieves url with signature.

This means it was signed with a GPG key it doesn't know. Are you sure you added it to your account previously (with `gpg key add`)?

**Comment by nolash** [comment]
yeah and the right key is in the `users.conf` in `./conf` too

**Comment by nolash** [comment]
also, if I give `--debug` it's not really outputing any more to the console...

**Comment by nolash** [comment]
Solved. The key in users.conf was:

* lowercase
* 4 bytes

By changing to uppercase and 8 bytes, it worked.

I'm not sure which one did the trick. though.
