### ISSUE TITLE
Clean replies

### ISSUE THREAD

**Issue by s7ntax** [ProgVal/Limnoria#1442]
Currently when I issue %quote random I get a reply prefixed with Quote #1: and suffixed with (added by s7ntax at 2021-01-24T16:12:21+0100). Is there a way to just have the bot give the quote with no prefix or suffix?

**Comment by ProgVal** [comment]
Hi,

You can set the config variabl `supybot.replies.databaseRecord` to the format you want. By default, it is `$Type #$id: $text (added by $username at $at)`; and you probably want just `$text`.

**Comment by s7ntax** [comment]
Thanks for the reply, i am getting this error

Error: 'supybot.replies.DatabaseRecord' is not a valid configuration variable.

**Comment by ProgVal** [comment]
You need to update Limnoria to 2020.05.15 or newer

**Comment by s7ntax** [comment]
haha it seems I am running supybot, I must have followed some old guide of how to install it as i didn't use apt, i'm running ubuntu 20.04 server. So if i have supybot do I need to remove that before installing limnoria?

**Comment by ProgVal** [comment]
yes

**Comment by ProgVal** [comment]
Ubuntu 20.04 is too old to have that version; try updating it to 20.10

**Comment by s7ntax** [comment]
I realised I installed using pip3 so i just updated it with pip3 and all is well. Thanks for the help
