### ISSUE TITLE
docu: certfp - wrong usage of ircquote

### ISSUE THREAD

**Issue by Lord255** [ProgVal/Limnoria#1474]
hi.

docu here:
https://limnoria-doc.readthedocs.io/en/latest/use/identifying_to_services.html#certfp

says we should use:
`owner ircquote NickServ cert add <fp>`

however it gives:

> INFO \<datetime\> supybot Received notice from NickServ on ******: "Invalid parameters for CERT.".
> INFO \<datetime\> supybot Received notice from NickServ on ******: "Syntax: CERT ADD|DEL|LIST|CLEAR [fingerprint]".

the following command did do the trick:

`owner ircquote privmsg nickserv :cert add`

list with:
owner ircquote privmsg nickserv :cert list

> DEBUG \<datetime\> supybot Outgoing message (**********): privmsg nickserv :cert list
> DEBUG \<datetime\> supybot Incoming message (**********): :NickServ!NickServ@***** NOTICE \<botnick\> :Fingerprint list for ^B\<botnick\>^B:
> DEBUG \<datetime\> supybot Incoming message (**********): :NickServ!NickServ@***** NOTICE \<botnick\> :- <fp>
> DEBUG \<datetime\> supybot Incoming message (**********): :NickServ!NickServ@***** NOTICE \<botnick\> :End of ^B\<botnick\>^B fingerprint list.

i think it should be updated.

**Comment by ProgVal** [comment]
I was made aware of this issue with Solanum yesterday. I reported it to them, but they don't consider it a bug.

The next release of Limnoria will have commands to privmsg nickserv without using ircquote, to work around this issue

**Comment by Lord255** [comment]
hi.
i just checked my other log, i thought unreal && anope is also affected, but you are right. i had this on solanum.

thx for the fast response and for handling. :)
nice project. (y)

**Comment by Mikaela** [comment]
> The next release of Limnoria will have commands to privmsg nickserv without using ircquote, to work around this issue

Is this going to be part of the services plugin and will it include https://github.com/ProgVal/Limnoria/issues/727 which freenode failed at again?

**Comment by ProgVal** [comment]
> Is this going to be part of the services plugin

yes

> will it include #727 which freenode failed at again?

no, unless `supybot.plugins.Services.NickServ` is set

**Comment by ProgVal** [comment]
Fixed in 4b829341315d7abb312dd1970e81943b53e599fe + 09943ffc54381443eb5678a94a6450a4428d77dc
