### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [ProgVal/Limnoria#1475]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine src/callbacks.py and observe `separatly`, however expect to see `separately`.
- Examine src/callbacks.py and observe `pluings`, however expect to see `plugins`.
- Examine src/drivers/__init__.py and observe `overrided`, however expect to see `overridden`.
- Examine src/registry.py and observe `explicitely`, however expect to see `explicitly`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/Limnoria/pull/new/bugfix_typos

Thanks.

**Comment by ProgVal** [comment]
Thanks. Can you rebase it on the `testing` branch and create a PR?

> To avoid wasting CI processing resources a branch with the fix has been prepared but a pull request has not yet been created.

You can also create a PR with `[skip ci]` in the description; it disables Travis-CI, GitHub Actions, etc.

**Comment by timgates42** [comment]
Thanks @ProgVal
