### ISSUE TITLE
Conflicting version number between pip and installed package

### ISSUE THREAD

**Issue by TrueBrain** [progval/Limnoria#1486]
Something you might be able to help me out with, to make automating upgrading Limnoria a bit easier:

Currently, Limnoria is published on pip as version `2021.07.21`. So automation picks up on this version. Great.

After installing however, the package turns out to announce itself as `2021.7.21` (mind the missing zero). In result, automation gets a bit conflicted .. the versions are not the same, but yet they are.

```
$ python3 -m venv test-venv
$ test-venv/bin/pip install limnoria==2021.07.21
$ test-venv/bin/python -m pip show limnoria
Name: limnoria
Version: 2021.7.21
Summary: A modified version of Supybot (an IRC bot and framework)
Home-page: https://github.com/ProgVal/Limnoria
Author: Valentin Lorentz
Author-email: progval+limnoria@progval.net
License: UNKNOWN
Location: test-venv/lib/python3.8/site-packages
Requires: 
Required-by: 
```

Is there any chance you can fix this discrepancy, and make my life a whole lot easier every month when updating? That would be truly awesome :D

Tnx, and tnx for maintaining this IRC bot, it is very much appreciated :)

**Comment by ProgVal** [comment]
It feels like a bug in pip itself; nothing in the installed metadata says the `2021.7.21` (grep on `test-venv/lib/python3.8/site-packages` to check), so it looks like pip parses then unparses it.

**Comment by TrueBrain** [comment]
If I would guess this is because pip assumes all versions are PEP 440 compatible. And that states that the major is 2021, minor is 7, patch is 21. Removing the zero makes sense in that case.

What is a bit annoying that pypi doesn't seem to follow PEP 440, which is a bit of a contradiction :D

A possible fix could be to use 2021.7.21 instead as version, which would be both PEP 440 and serves your purpose, I would think.

**Comment by ProgVal** [comment]
Zeros are explicitly permitted by the PEP:

"All integers are interpreted via the int() built in and normalize to the string form of the output. This means that an integer version of 00 would normalize to 0 while 09000 would normalize to 9000." https://www.python.org/dev/peps/pep-0440/#integer-normalization

"For example, if a project is using date based versions like 2014.04" https://www.python.org/dev/peps/pep-0440/#id30

The PEP only states they are equivalent.

**Comment by TrueBrain** [comment]
Haha, you are not wrong :D

So it is pip being a pita here :) meh.

**Comment by TrueBrain** [comment]
In the year 2022, all packages published were without a heading-zero. I don't know if you did that yourself, or that the ecosystem figured this out, but either way, I am really happy with it. Had zero issues upgrading this library for the whole year, so awesome job :)

With that, I also think it is time to close this bug, as it is no longer relevant. If you disagree, feel free to reopen it, but how things went in 2022 makes me most happy :)

Tnx!
