### ISSUE TITLE
when a plugin adds a duplicate command

### ISSUE THREAD

**Issue by PaFra75** [progval/Limnoria#1515]
When a plugin adds a duplicate command does that override the existing one?

Could I access both commands?

**Comment by progval** [comment]
It looks like this:

```
05:51:53 <val> @calc
05:51:54 <Limnoria> val: Error: The command "calc" is available in the Google and Math plugins.  Please specify the plugin whose command you wish to call by using its name as a command before "calc".
```

**Comment by PaFra75** [comment]
That behavior is better than what I was hoping for. Should I close the issue or do moderators do such things?

**Comment by progval** [comment]
either of us can close it
