### ISSUE TITLE
Cryptographic API Misuse Vulnerability

### ISSUE THREAD

**Issue by lialon** [progval/Limnoria#1587]
### Description:

In the "Limnoria/plugins/Fediverse/activitypub.py", I have identified a security vulnerability about insecure cryptographic algorithm. PKCS1v1.5  is vulnerable to the chosen-ciphertext attack.

### Location:

https://github.com/progval/Limnoria/blob/master/plugins/Fediverse/activitypub.py#L251

```python
signed_text.encode(), padding.PKCS1v15(), hashes.SHA256()
```

### Reference

- **CWE-780: Use of RSA Algorithm without OAEP**

### Recommendations:

Try using other padding(OAEP) instead of PKCS1v1.5.

**Comment by progval** [comment]
Tell that to the authors of https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures

And please don't spam dozens repositories with low-quality reports straight from a vulnerability scanner.
