### ISSUE TITLE
Karma add setting to share the karma between channels

### ISSUE THREAD

**Issue by ThatLurker** [progval/Limnoria#1597]
Would it be possible to get a setting where you could toggle the karma to be shared between channels.
So karma changes in one channel would reflect the changes in another channel.

**Comment by progval** [comment]
You can use `supybot.databases.plugins.channelSpecific.link`, but it will apply to all plugins, not just Karma. Would that work for you?

**Comment by ThatLurker** [comment]
Ohh in this instance that works perfectly. Thanks
