### ISSUE TITLE
Services plugin does not allow network-specific NickServ password

### ISSUE THREAD

**Issue by ProgVal** [ProgVal/Limnoria#23]
NickServ password is not network-specific, while it should be. One could use the same password for the bot on all networks, but that's a bad idea. Alternatively, one could use different nicks for the bot on every network, but again, that shouldn't be necessary.

Report originally made by nyuszika7h at https://github.com/ProgVal/Limnoria/issues/22

**Comment by weedy** [comment]
Even trying to use SASL means I can't ghost.
Now that I have the password unconfigured OR I configure it for ONE network which makes it wrong for every other network, ghosting is broken. And when my old connection finally dies the bot doesn't try to get it's old nick back.

**Comment by ProgVal** [comment]
Implemented in b65d78518cb98a0f90cfc976336b78b72ef52c02.

**Comment by ProgVal** [comment]
Actually no, because it's available with the Config plugin but not the `services password` command.

**Comment by ProgVal** [comment]
Oh wait actually it is. :)
