### ISSUE TITLE
Add in encode/decode to ircutils?

### ISSUE THREAD

**Issue by atr000** [ProgVal/Limnoria#359]
I see a bit of encode('utf-8') within plugins and maybe this would be useful to include in ircutils so returning an encoded string doesn't fail?

def decode_utf8(string):
    """ Returns the given string as a unicode string (if possible).
"""
    if isinstance(string, str):
        try:
            return string.decode("utf-8")
        except:
            return string
    return unicode(string)

def encode_utf8(string):
    """ Returns the given string as a Python byte string (if possible).
"""
    if isinstance(string, unicode):
        try:
            return string.encode("utf-8")
        except:
            return string
    return str(string)

**Comment by jlu5** [comment]
I don't think this is relevant anymore as Limnoria now requires Python 3. Now, there's a clear separation between strings and byte sequences.
