### ISSUE TITLE
Feature request: ShrinkURL: Add support for bit.ly

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#361]
It has analytics.

[Bitly api documentation](http://dev.bitly.com/)

**Comment by t3chguy** [comment]
Mikaela, I have just implemented this. It is in the testing branch, https://github.com/ProgVal/Limnoria/pull/1121

**Comment by ProgVal** [comment]
Hmm, re-reading this comment I wrote makes me doubt merging this was a good idea
