### ISSUE TITLE
Have a separate config variable for IPv4 and IPv6 vhosts

### ISSUE THREAD

**Issue by nyuszika7h** [ProgVal/Limnoria#517]
Here are some possible ways I have thought of:

1. Use `supybot.protocols.irc.vhost4` and `supybot.protocols.irc.vhost6`
2. Use `supybot.protocols.irc.vhost` and `supybot.networks.<network>.vhost`
3. Use 2 with `vhost4` and `vhost6`

The third option is the most flexible, in case you have both IPv6 and IPv4 servers for an IRC network.

**Comment by Mikaela** [comment]
In reply to my previous comment `2015-02-22 11:54:46+0200 <@Limnoria> supybot.protocols.irc.vhost and supybot.protocols.irc.vhostv6`, this issue looks like this is already done.
