### ISSUE TITLE
python3 uses wrong encoding for aliases

### ISSUE THREAD

**Issue by o11c** [ProgVal/Limnoria#550]
After switching my bot from python2 to python3, all my non-ascii aliases are messed up

As an example, the conf file contains: \xef\xbd\xa1\xe2\x97\x95\xe2\x80\xbf\xe2\x80\xbf\xe2\x97\x95\xef\xbd\xa1
which is the correct utf-8 version of: ｡◕‿‿◕｡
but under python3, it instead decodes it as iso-8859-1, yielding: ï½¡ââ¿â¿âï½¡

**Comment by ProgVal** [comment]
Alias is not supposed to handle non-ascii characters. I recommend the Aka plugin for these.

**Comment by GLolol** [comment]
A bit offtopic, but is there a reason why there are two alias plugins (Alias and Aka) still being maintained? The latter can already import databases for easy migration.

**Comment by ProgVal** [comment]
Removing Alias from the source would make it impossible to migrate without rolling back the update.
