### ISSUE TITLE
Owner or Admin: add commands to perform command on all servers / channels.

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#686]
Some IRC clients have commands like `/allserv`, `/allchan` and `/allchanl`.
1. Executes command on all serveres.
2. Executes command on all channels on all servers.
3. Executes command on all channels on current server.

Oh, and I mean bot commands, not raw commands.

And if the command changes default configuration, it should be applied to global and channelspecific variables.

**Comment by GLolol** [comment]
Fixed by #1305 (that PR isn't written to auto-close this issue)
