### ISSUE TITLE
Make Filter.uniud ignore non-ascii characters instead of responding with errors.

### ISSUE THREAD

**Issue by monodemono** [ProgVal/Limnoria#716]
```
Error: UnicodeDecodeError: 'ascii' codec can't decode byte 0x__ in position 0: ordinal not in range(128)
```

The __ changes depending on where the first unicode character appears in the message.

This just seems sloppy and would confuse users. If possible, the bot should just ignore non-ascii characters, and flip as much of the string as it can (with the non-ascii characters removed).

**Comment by jlu5** [comment]
This issue seems specific to Python 2 - as Limnoria now requires Python 3, I'm closing this accordingly.
