### ISSUE TITLE
CTCPs are not relayed correctly - Relay just relays it as a normal message.

### ISSUE THREAD

**Issue by Limnoria** [ProgVal/Limnoria#75]
Issue sent from #limnoria at freenode by nyuszika7h (registered as nyuszika7h)

**Comment by Mikaela** [comment]
Shouldn't CTCPs just be stripped entirely? Or what is the use on the bot receiving CTCP replies on the other side(s) of relays?

**Comment by GLolol** [comment]
It looks like this was implemented in 2010? 455b5631bc935f3d3689a535976c249b4cbab70d

https://github.com/ProgVal/Limnoria/blob/master/plugins/Relay/plugin.py#L268-L270 looks correct too.
