### ISSUE TITLE
core/SASL: show which mechanism fails/succeeds

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#846]
Some messages say PLAIN/EXTERNAL, others don't. I don't have examples at the moment, but if you look at connect messages, you should encounter messages which talk about SASL without mentioning which mechanism especially if you have both PLAIN and EXTERNAL configured.

**Comment by ProgVal** [comment]
Fixed by 04b55805b8175e0f29d0f4d77dbae2b91b96d5d1.
