### ISSUE TITLE
ReDoS attack via 'quote search --regexp' if the quote DB is large enough

### ISSUE THREAD

**Issue by IonCannon218** [ProgVal/Limnoria#855]
Doing `quote search --regexp "/.*.*.*.*.*.*.*invalid/"` would spam the not found message after accumulating enough errors before that. But, if there is enough of the repeated `.*` in the regex, the bot seems to create multiple instances of itself. The bot owner says this actually crashed the computer running the bot.

Logs: https://gist.github.com/IonCannon218/15d344aef757982980d0

**Comment by IonCannon218** [comment]
Reproduced: https://gist.github.com/IonCannon218/38120043c45a56fe6d97
Seems to require high uptime with enough use of the bot.

The bot(s) uptime was:
>I have been running for 11 weeks, 0 days, 12 hours, 39 minutes, and 59 seconds.

**Comment by GLolol** [comment]
Confirming this issue - it looks like it gets progressively worse as the quote database grows, since a separate process is spawned for each quote, and these quickly hit the 0.1 regexp_wrapper timeout quickly.
