### ISSUE TITLE
Supybot fails to reconnect when it misses a PING response

### ISSUE THREAD

**Issue by ballock** [ProgVal/Limnoria#866]
<pre>
DEBUG 2014-10-05T22:23:57 supybot Incoming message (ircnet): :ircs.ircnet.com PONG ircs.ircnet.com :1412547836
DEBUG 2014-10-05T22:25:29 supybot Incoming message (ircnet): PING :ircs.ircnet.com
DEBUG 2014-10-05T22:25:29 supybot Outgoing message (ircnet): PONG :ircs.ircnet.com
DEBUG 2014-10-05T22:25:58 supybot Outgoing message (ircnet): PING :1412547957
WARNING 2014-10-05T22:27:57 supybot Ping sent at 2014-10-05T22:25:57 not replied to.
DEBUG 2014-10-05T22:27:57 supybot Incoming message (ircnet): ERROR :Ping sent at 2014-10-05T22:25:57 not replied to.
WARNING 2014-10-05T22:27:57 supybot Error message from ircnet: Ping sent at 2014-10-05T22:25:57 not replied to.
INFO 2014-10-05T22:27:57 supybot Reconnecting to ircnet.
</pre>
...
<pre>
WARNING 2014-10-06T08:52:04 supybot Ping sent at 2014-10-05T22:25:57 not replied to.
DEBUG 2014-10-06T08:52:04 supybot Incoming message (ircnet): ERROR :Ping sent at 2014-10-05T22:25:57 not replied to.
WARNING 2014-10-06T08:52:04 supybot Error message from ircnet: Ping sent at 2014-10-05T22:25:57 not replied to.
INFO 2014-10-06T08:52:04 supybot Reconnecting to ircnet.
</pre>
...and so on for hours. Limnoria fails to reconnect, it's not on the channels. It's complaining about missing a Ping response from the particular time, but the server would not remember to send a PONG to something that was requested long before.

a CTRL-c produced:
<pre>
INFO 2014-10-06T08:52:05 supybot Exiting due to Ctrl-C.  If the bot doesn't exit within a few seconds, feel free to press Ctrl-C again to make it exit without flushing its message queues.
DEBUG 2014-10-06T08:52:05 supybot Writing registry file to .supybot/pybot.conf
DEBUG 2014-10-06T08:52:05 supybot Finished writing registry file.
DEBUG 2014-10-06T08:52:05 supybot Regexp cache size: 93
DEBUG 2014-10-06T08:52:05 supybot Pattern cache size: 1
DEBUG 2014-10-06T08:52:05 supybot HostmaskPatternEqual cache size: 190
INFO 2014-10-06T08:52:05 supybot Flushers flushed and garbage collected.
DEBUG 2014-10-06T08:52:05 supybot Outgoing message (ircnet): QUIT :Ctrl-C at console.
WARNING 2014-10-06T08:52:05 supybot Ping sent at 2014-10-05T22:25:57 not replied to.
DEBUG 2014-10-06T08:52:05 supybot Incoming message (ircnet): ERROR :Ping sent at 2014-10-05T22:25:57 not replied to.
WARNING 2014-10-06T08:52:05 supybot Error message from ircnet: Ping sent at 2014-10-05T22:25:57 not replied to.
INFO 2014-10-06T08:52:05 supybot Reconnecting to ircnet.
INFO 2014-10-06T08:52:05 supybot Driver for Irc object for ircnet dying.
INFO 2014-10-06T08:52:05 supybot Irc object for ircnet dying.
INFO 2014-10-06T08:52:05 supybot Driver for Irc object for ircnet dying.
DEBUG 2014-10-06T08:52:05 supybot Last Irc, clearing callbacks.
INFO 2014-10-06T08:52:06 supybot Total uptime: 2 weeks, 3 days, 21 hours, 14 minutes, and 15 seconds.
INFO 2014-10-06T08:52:06 supybot Total CPU time taken: 570.4 seconds.
INFO 2014-10-06T08:52:06 supybot No more Irc objects, exiting.
INFO 2014-10-06T08:52:06 supybot Shutdown initiated.
INFO 2014-10-06T08:52:06 supybot Killing Driver objects.
INFO 2014-10-06T08:52:06 supybot Killing Irc objects.
INFO 2014-10-06T08:52:06 supybot Writing registry file to .supybot/pybot.conf
INFO 2014-10-06T08:52:06 supybot Finished writing registry file.
INFO 2014-10-06T08:52:06 supybot Shutdown complete.
</pre>
edit: formatting

**Comment by GLolol** [comment]
I've been experiencing this too lately, though I get an error message. The bot just doesn't reconnect to the network until I run `disconnect` and `connect`, though other networks' connections are still fine.

```
WARNING 2015-03-11T09:13:34 Error message from freenode: Ping sent at 2015-03-11T09:11:34 not replied to.
INFO 2015-03-11T09:13:34 Reconnecting to freenode.
ERROR 2015-03-11T09:13:34 Uncaught exception in Irc.takeMsg:
Traceback (most recent call last):
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/log.py", line 361, in m
    return f(self, *args, **kwargs)
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/irclib.py", line 778, in takeMsg
    self.driver.reconnect()
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/drivers/Socket.py", line 266, in reconnect
    self.irc.reset()
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/irclib.py", line 907, in reset
    callback.reset()
TypeError: reset() missing 3 required positional arguments: 'irc', 'msg', and 'args'
ERROR 2015-03-11T09:13:34 Exception id: 0xcf899
```
I run a [slightly diverging fork](https://github.com/ProgVal/Limnoria/compare/testing...GLolol:corona) of the bot on Python 3.4, but since I haven't changed any of the connection-handling internals I'd assume the issue applies here too.

**Comment by ProgVal** [comment]
Run this command on your plugins directory(ies):

```
grep "def reset.*irc" . -r
```

Any plugin matching this should be fixed in order not to have a command
named `reset`.

**Comment by GLolol** [comment]
Oh. Is that not allowed?

**Comment by ProgVal** [comment]
I guess that issue is solved.

**Comment by GLolol** [comment]
Are there any other reserved function names that plugins must not use to define functions? Is this documented anywhere?

**Comment by ProgVal** [comment]
not really
