### ISSUE TITLE
Fun & Games with OpenShift (AKA Making bot usable on PAAS)

### ISSUE THREAD

**Issue by Efreak** [ProgVal/Limnoria#896]
I'm running supybot on openshift, but I've encountered a few problems that should actually be relatively simple to solve.

I'm modifying the sourcecode directly to use environment variables. Can you add an expander for `os.environ['some_var']`? The best way would probably be to expand _any_ environment variable. It should be available for file locations, ip address, port, etc.
I've removed references to addresses6 and replaced addresses4 with `addresses4 = [(4, (os.environ['OPENSHIFT_DIY_IP'], int(os.environ['OPENSHIFT_DIY_PORT'])))]`

Also, botchk should be able to either grab a tail of a log in some way other than using pipes, as pipes aren't allowed, or it should gracefully fail on that and just know that the bot's running but inaccessible.
`PermissionError: [Errno 13] Permission denied`

If supybot webserver logs incoming ip addresses, it should be able to parse the X-Forwarded-For and so forth (I haven't checked this, because I simply don't care).

This is all that's required for getting supybot running on heroku, openshift, etc. Supybot is difficult to set up on openshift's python cartridges, but I can provide a step-by-step of how I set it up on their DIY cartridge if you want.

**Comment by rnc** [comment]
@Efreak @ProgVal I have a working installation now of Limnoria on OpenShift V3 (I have tried it running locally via minishift or a hosted cluster). It is using https://github.com/rnc/docker-limnoria which is derived from your https://github.com/ProgVal/docker-limnoria ; I am happy to send a PR for that although it is a bit different currently.
