### ISSUE TITLE
[meta] Debian auto-builds should include the date in the version number

### ISSUE THREAD

**Issue by jlu5** [ProgVal/Limnoria#933]
On Debian and Ubuntu, version numbers are used by APT to tell what versions are newer than others. In the current version scheme, (e.g. `0.83.4.1+limnoria+master~gitd4e07c7`), the commit hash is used, but this isn't really a good indicator of how old or new a version is. For example, commit 654df6f is newer than commit 99a947e, but `dpkg` will think that 99a947e is a greater version ( 9 > 6) and warn about the package being downgraded. In reality, an upgrade is happening. 

The Fedora builds do this already. Including the date (before the commit number) would be a better solution, since something like `2014.12.06` will be numerically greater than `2014.11.21`.

**Comment by ProgVal** [comment]
No more Debian autobuilds, closing issue.
