### ISSUE TITLE
Error: We broke The Google! [Keeping open in case Google removes the API (again)]

### ISSUE THREAD

**Issue by Mikaela** [ProgVal/Limnoria#955]
> Error: The Google Web Search API is no longer available. Please migrate to the Google Custom Search API (https://developers.google.com/custom-search/)

```
2014-12-18 17:53:10+0200 < tacocat> 07:53 <+synnero> `google .
2014-12-18 17:53:10+0200 < tacocat> 07:53 <@Lily> Error: The Google Web Search API is no longer available. Please migrate to the Google Custom Search API (https://developers.google.com/custom-search/)
2014-12-18 17:56:00+0200 < tacocat> Mikaela: i modded my bot to actually show the real error message instead of a generic one
```

* * * * *

*Description edited to show the actual error message and source for it and remove the wondering if the API got removed, because as we can see, it did get removed.*

**Comment by GLolol** [comment]
Update: I also have a [DDG](https://github.com/GLolol/SupyPlugins/tree/master/DDG) plugin that works somewhat similarly to Google. It allows retrieving multiple results and showing snippets of websites.

It requires no API keys and simply parses DuckDuckGo's JS-free Lite site: https://duckduckgo.com/lite?q=supybot.

**Comment by Mikaela** [comment]
Update: for some reason gribble complains about this, but Limnoria works.

**Comment by GLolol** [comment]
Both the `google` and `translate` commands are restored in testing; should this be closed now? There's really nothing that can be done about Google's API instability in the long term, unless it is replaced entirely.

**Comment by Mikaela** [comment]
> unless it is replaced entirely.

Yes, this cannot be resolved any other way than replacing Google. DDG would probably be the best option for search commands, no idea about translate other than DDG doesn't have it. I don't know about the APIs of alternatives either meaning Bing/Yahoo.

**Comment by Mikaela** [comment]
I believe this has been possibly fixed in testing, but since I am not affiliated with Limnoia anymore, I don't know surely.

However I am closing this in favour of https://github.com/ProgVal/Limnoria/issues/1238.

**Comment by GLolol** [comment]
What does "affiliated" even mean, and how does it relate to this situation?
