### ISSUE TITLE
assertError() doesn't work properly if reply.showsimplesyntax is set to True

### ISSUE THREAD

**Issue by jlu5** [ProgVal/Limnoria#981]
I decided to spin up a custom mod of Limnoria a while ago, with custom defaults in `src/conf.py`. One of these includes setting `reply.showsimplesyntax` to True by default, but this causes many tests to fail on `assertError`!

Although this isn't currently an issue in stock Limnoria (`showsimplesyntax` is disabled by default), a config option should not cause unrelated tests to fail.

A snippet from `$ supybot-test Conditional/`:

```
FAIL: testNne (Conditional.test.ConditionalTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/test.py", line 154, in runTest
    originalRunTest()
  File "./Conditional/test.py", line 114, in testNne
    self.assertError('nne 1 2 3')
  File "/home/gl/.local/lib/python3.4/site-packages/supybot/test.py", line 282, in assertError
    '%r did not error: %s' % (query, m.args[1]))
AssertionError: False is not true : 'nne 1 2 3' did not error: nne <item1> <item2>

----------------------------------------------------------------------
Ran 17 tests in 6.474s

FAILED (failures=7)
```

**Comment by ProgVal** [comment]
I don't think it's a bug, lots of tests would break with non-default configs (eg. not replying on error, replying with notices, etc.)

**Comment by jlu5** [comment]
Yeah, let's close this as wontfix since my previous use-case for this issue is no longer there.
